/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_19471.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_92626.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105626.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_9698.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159766.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_145233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206923.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86582.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_4175.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_208897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_104207.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_173731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_184547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155408.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_18853.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_33465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_51337.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_14764.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_160321.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178574.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_163037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42189.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_67639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99417.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_46811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6816.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_126479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_168560.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178273.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196438.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80635.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_208003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_153064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_119151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_54967.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_63243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202665.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_4768.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94881.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159351.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154367.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101344.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206708.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_9051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_59342.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_40711.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_217030.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_5197.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_104490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_127619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_47891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_61589.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_167373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38868.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187082.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_214611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87011.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120550.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142760.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129030.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_59602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_173468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58381.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116119.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_147188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_124299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_63251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49541.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216451.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142922.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_90943.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_150056.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_205944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_190738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192690.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_104679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_19057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177440.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74712.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58077.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_115453.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_60748.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195762.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195379.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_33978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85508.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_131027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_112396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_50375.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20183.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149292.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_125450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_63115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116487.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_180213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_214215.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_63159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_156379.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_124386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174968.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_191174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_153358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174753.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16024.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193670.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27457.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25755.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25356.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_62722.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27967.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_176287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2148.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_50094.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45100.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_59205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199407.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42464.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178307.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_15189.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_147446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135538.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_181498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114689.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138261.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_122929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_67277.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129253.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121328.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44119.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_145378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_128231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_69193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_31135.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_214138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44626.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206920.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132022.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_183154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77829.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_183114.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148781.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_31498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21936.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_78420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_89528.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216113.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_185639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_31191.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_180677.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87388.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_190561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_150254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21220.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_171043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213532.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35454.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_200919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36771.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_111285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_156087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_65318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_172836.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135069.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74255.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199841.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195302.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_205032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_201223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53801.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87314.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_61276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177806.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195277.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162768.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8809.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86994.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_141834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162886.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_180976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86307.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_23917.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_71240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170119.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13688.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_140134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_41956.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_217614.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_190322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26724.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_67139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_71761.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142592.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_28730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_163446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44121.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_164326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_168643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_176577.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_153700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48257.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20773.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_82482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216746.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95607.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198748.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_140857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_153230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98886.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35005.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_185206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_4101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27527.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_92099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158732.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_165051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_111383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_52610.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_23829.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_89391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_122543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_67837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_131262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_205688.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_31578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114875.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_10685.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_185019.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_122503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88610.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1489.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_112966.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121545.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110148.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161796.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_47253.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74296.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_34830.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_60828.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_10460.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143574.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_139437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_131500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_33988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_76668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_128809.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_127566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_147959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_124258.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_92268.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_61510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_152381.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38930.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75764.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_217587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_19389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_173907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_73341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106529.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120155.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_124218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_40821.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_89393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_180543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_40963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_73156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_31298.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_126225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_130621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_23600.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_122348.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_184682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75178.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_181297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_7855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_185071.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_111988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195817.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120874.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186471.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_69539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_92781.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_119669.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_113357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_215734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_64943.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_65770.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_5096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_122066.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_100331.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134454.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_139484.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_65185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_72003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_103873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96772.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123724.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_69523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_169344.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_34899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_122626.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209859.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8796.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80818.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142426.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_83225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_54983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_100313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102795.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101821.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44901.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_5440.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_171273.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_33521.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129786.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_64023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77648.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105011.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_201885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_128147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88263.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_180009.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_46723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_31014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_115037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116256.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_59349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_73073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_164873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211080.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_185207.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210418.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_128368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129913.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193961.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_90646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87921.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_46508.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_191582.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107394.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_104112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_92462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212455.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_31019.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_61111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175502.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_188109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_160101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_82706.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_67850.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_84045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177822.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_9365.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97859.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79220.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_203618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157808.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_124964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138252.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_69053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_33686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_19477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_112140.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189431.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49061.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_31925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_76898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_180658.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_61709.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199918.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_7367.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105321.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_64610.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_62591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36829.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3140.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_73489.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45918.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_63679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_63355.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117387.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_89825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99588.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_140447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_28865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_111675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_34600.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121298.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_78896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_54819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_203328.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_119977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142438.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_164657.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_33345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206689.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_51531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77141.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_46795.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_34717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_141839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_23960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_34557.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_78563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_181894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_139460.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_172341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_126123.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_115769.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98264.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29979.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105029.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48365.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_169960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_66286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202399.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_180893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36634.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154958.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211372.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195475.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178255.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_113131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_140943.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149722.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39215.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_23372.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_147625.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_71654.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_215317.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_128343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_92571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21171.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20430.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_62772.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45183.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_65915.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_140034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192775.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_78386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_52518.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155768.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_40192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_28784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189196.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13321.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_67143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_169569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193019.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_15924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_92621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210762.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192440.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_46430.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_9696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_200266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138121.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_63718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149932.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_151438.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1744.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_33277.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_64752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_151523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17178.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_124726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_52062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_185842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_76213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108763.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_167993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_43763.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_152954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118955.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198076.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_115188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_5955.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29818.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_184426.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_126546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_60606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_28445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_191065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_7969.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193651.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75836.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_19774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137936.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_54982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178216.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202219.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_131126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_165975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_203161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_191743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210916.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45568.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136812.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_4425.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_92168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_188679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_139795.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_150822.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_194889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_33556.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_92073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133985.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_5530.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_141789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27081.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_67415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27836.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116063.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178622.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_47147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_104729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_112215.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_46736.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_10675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24041.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_130176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116688.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116381.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_194787.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_43451.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99874.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98312.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48541.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_72090.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1545.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_126201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8029.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97074.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_89105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2589.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_205433.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_188826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178755.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206518.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209955.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_130671.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42305.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_41671.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_51611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_152164.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_47105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_60085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144835.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99094.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_113903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105366.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129821.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_140142.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_66036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146295.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_41063.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11532.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68211.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_73960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162716.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_152094.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157407.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44511.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_5463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_14775.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_81089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_92552.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_69809.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_73342.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_184272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_104101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_214466.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_122224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_172303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_89435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_33624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88800.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_147887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212881.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_47673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_169163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170220.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_145867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_81426.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_183539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_180720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_164786.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_188203.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_64501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96550.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216171.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159604.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_60262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98142.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_37306.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_130348.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42710.qa.bqv
