/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_79880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_156086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_3154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_165996.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_221644.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_144851.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_18625.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_116243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_98586.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_261173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_95870.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_226486.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_169834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_239126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_120431.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_41064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_84843.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_164394.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_17987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_215672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_151582.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_148167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_244981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_194512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_102154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_251692.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_191111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_92676.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_120322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_55285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179830.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_231670.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217374.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_260638.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_233112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_246443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_99241.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_210547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_14843.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_245448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_88738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_51205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_212135.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_18894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_65236.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_194776.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_80043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_229879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_128672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_118533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_196636.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_78852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_218856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_233605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_188052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_228230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_127648.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_163561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_123736.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_6290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_186223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_234038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_89062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_70844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_213971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_214036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_237493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_180175.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_218266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_214150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_121007.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_171875.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_244943.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_95898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_143172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_230063.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_205479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_85820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184202.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_243761.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_145892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_189402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_172058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_75411.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_221531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_169441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_92411.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_13954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_127298.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_209735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_39627.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_216819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_231311.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_225728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_99553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_223823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_180522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_38485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_37585.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_232502.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_234625.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_34188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_237253.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_248022.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_169590.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_133644.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_31113.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_151049.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_54612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_73314.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_234854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_61927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_145919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_229114.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_96304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_257671.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_243398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_96154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_95983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_96041.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_189256.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_123621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_16759.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_116921.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_39078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_158797.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_258309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_238396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_134531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_90831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_201457.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_183036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_197898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_48626.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_8532.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_93062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_195642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_9989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_204102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_207354.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_44374.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_57016.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_194017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_146844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_226333.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_131699.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_134480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_245296.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_253450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_67003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_13001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_141568.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_76341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66090.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_97001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_199001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_164131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_247076.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_39806.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_190339.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_89468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_105239.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_126560.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_208621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_80128.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206238.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_91443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_170674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_148531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_242774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_47481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_1334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_209373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_28947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_229647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_20781.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_7186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_245897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_174292.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_13640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_204538.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_99112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_193485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_147232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_236205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_87530.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_215900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_114592.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_110088.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_136381.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_250649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_167356.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_83290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_163276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_193509.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_183947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_118472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_251056.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_15264.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_98827.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_90663.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_177111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_157640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_232626.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_121441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_201532.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_236610.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_26103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_39018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_95627.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_129698.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_94845.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_146280.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_149798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_118021.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217440.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_47032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_258979.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_163649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_94253.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_190853.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_101352.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_1709.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_109422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_55970.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25708.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_92065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_160016.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_67444.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_156367.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_231997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_27556.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_50667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_211649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_92259.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_192796.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_149295.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_92174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_210024.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_34598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25541.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_198453.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_221558.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_177934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_75090.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_247586.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_208147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_212292.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_213009.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_99793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_5090.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_110164.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_119497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_1678.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_214918.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_231287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_221295.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_180368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_122920.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_117732.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_108137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_145115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_81611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_235045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217973.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_52435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25967.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_64176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179331.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219092.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_244455.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_162833.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_216913.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_78270.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_174191.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_95187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_251654.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_143704.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_176164.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_223964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_97317.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_232535.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_191383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_29121.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_156404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_196853.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_173893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_41713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_122155.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_209558.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179381.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_110783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_122309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_20233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_227609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256457.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_95084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_125666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_7428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_2945.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_60695.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_64942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_31052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_36037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_237820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_255245.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_137117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_93388.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_245479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_118838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_113575.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_82402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_192869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_45334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_19128.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_150989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_255895.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_137250.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_244347.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179344.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_60332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_123396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_12167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_24640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_81449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_191485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_81432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_187248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_216553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_204890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_163938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_86655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_73459.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_158192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_119611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_5087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_91082.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_222150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_261234.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219755.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_83342.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_31394.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_76423.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179427.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_129371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_234943.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_252850.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_188720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_77897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_722.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_244936.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_130096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_239016.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_112304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_195033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_244844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_55501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_52494.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_171871.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_161418.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_215977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_34445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_46423.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_54169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_98514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_18898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_145163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_49184.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_141117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_13467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_3138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_81846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_37700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_210493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_47432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_176075.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_257973.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_27653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_48053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_202187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_26059.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_255050.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_136692.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_99734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_14592.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_178420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_260873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_118226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_35156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_46660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_28096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_133417.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_23835.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_97744.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_119383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_191782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_127563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_158937.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_140701.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_81577.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_230568.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_240281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_28928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_216227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_91345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_22880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_252391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_183969.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_135200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_244987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_60436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_213424.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_65113.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_11272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_165035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_117133.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_247314.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_114702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_162559.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_47554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_113338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_83272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_223432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_20764.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_127262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_106456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_19552.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_192913.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184438.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_26153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_131533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_64742.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_185367.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_101404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_90297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_188565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_239505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_195915.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_224432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_59101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_237933.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_111365.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_48598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_203334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_101430.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_251676.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_91183.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_145934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_93597.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_108448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_46821.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_1639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_2203.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_62145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_207407.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_197097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_126627.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_222477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_154737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_14381.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_208501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_38963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_26978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_7028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_242918.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_250673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_15023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_151083.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_43052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_126632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_35204.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_245689.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_41477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_182840.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_158097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_122649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_89039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_159962.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_96673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_242139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_198242.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_108644.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_85470.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_75339.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_5164.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_101903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_227499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_250167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_164443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_125682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_138347.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_121540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_252623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_107819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_174093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_240501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_261245.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_52936.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_126344.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_124181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_54469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_260549.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_57147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_125645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241689.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_118690.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_90330.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_231331.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_13034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_3412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_80331.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_61928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_170802.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_103122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_47607.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_87336.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_69637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_26372.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_190446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_204854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_220482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_187208.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_253599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_164354.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_90525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184685.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_175893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_223162.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_191894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_17614.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_230965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_240598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_195405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_6526.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_191999.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_125265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_31793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_130700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_78507.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_253944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_237781.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_59975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_99683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_210468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_38133.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_104170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_257741.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_94602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_207630.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_262000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_177863.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_166571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_140604.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_190654.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_182065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_33440.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_213294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_83080.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_251505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_183916.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_17944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_87515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_22483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_171490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_75982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_101320.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_150781.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_187053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_175490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_78612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_76804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_52667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_118828.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_38010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_148959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_54573.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_224903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_56431.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219586.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_12724.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_230111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_185725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_105919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_21319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_12718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_114741.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_55431.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_52149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_126631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_127783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_249962.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_248232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_175792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_13676.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_106297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_16002.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_4721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_116615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_237199.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_120397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_229771.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_122217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_27921.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_60354.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_68384.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_185461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_27965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_124923.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_207783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_148312.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_88458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_56269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_101946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_108415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_50634.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_112717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_7673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_169320.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_214060.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_114498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_51308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_214349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_12777.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_189230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_235224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_178578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_243505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_224143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_35014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_140938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_74777.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_33584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_74964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_144294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_246590.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_126505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_56824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_20807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_161181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_167863.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_79060.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_56462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_110369.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_245669.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_87379.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_213043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_200318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_23724.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_145213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_23271.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_136469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_843.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_83256.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_159907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_155642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_213897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_252136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_211418.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_200946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_246980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_76374.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_120139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_92464.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_2126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_78213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_49676.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_113051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_22486.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_204937.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_106220.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_176027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_140662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_258480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_227958.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_126961.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_30546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_6736.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_59171.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_40326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_87093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_247399.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_118364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_60351.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_247365.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_199064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_107182.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_87376.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_140488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_83695.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_236038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_239024.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_156713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_15696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_235085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_50386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_164049.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_103578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_183229.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_136973.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_231911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_213762.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_51270.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_188700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_205623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_220913.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_8478.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_39631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_233193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_21571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_188384.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_108496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_46871.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_110691.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_44047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_152520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_125014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_22404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_88899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_74919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_81435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_74218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_104498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_121382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_15155.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_237484.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_60813.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_87705.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_215594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_126125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_63014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_38487.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217901.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_98315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_150976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_57051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_248080.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_188690.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_36718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_173412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_165058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_258033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_29230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_254306.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_211759.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_161537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_93019.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_181094.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_199363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_131363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_121572.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_166114.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_19436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_26505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_124660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_68125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_181531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_71928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_111975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_5633.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_110643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206353.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_40105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_57796.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_4575.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_119700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_47242.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_229615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_171185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_54669.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_40226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_35490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_168092.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_95246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_201290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_73291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_122947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_13910.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_45583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_75790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_244390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_251023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_78446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_4513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_252948.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_88430.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_152560.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_92324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_81293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_115847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_141682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_252872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219367.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_84836.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_58230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_151969.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_53864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_43856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_190473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_156374.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206183.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_159740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_109135.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_250822.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_142039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_254265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_227705.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_159909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_6186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_183447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_107238.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_212495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_183497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_19534.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_218928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_1156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_180734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_31674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_164961.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_110580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_132832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206321.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_16932.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_202234.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_227576.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_40975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_223640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_69953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_44938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_253150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_151506.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_196642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_143170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_59395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241114.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_170153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_69531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_70926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_248750.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_144184.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_1617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_57671.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_37166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_199054.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_135213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_35624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_81085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_101436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_37020.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_227891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_119632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_31595.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_90281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_104445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_30089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_49201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_65728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_76174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_54218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_126456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_114057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_70237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_194469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_94301.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_162893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_180941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_133431.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_240988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_232109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_100183.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_9586.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_158703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_171730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_43667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_174701.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_238316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_165867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_228285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_78729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_11165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_230266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_7953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_232530.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_55314.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_159917.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_34836.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_69684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_163806.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_247030.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_202720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_1731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_253047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_235792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_124306.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_53810.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_187755.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_167198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_233913.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_79486.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_253656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_248923.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_259444.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_230054.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_121985.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_141274.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_11914.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_92529.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_62989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_75147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_135800.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_176151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_163319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_192730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_109490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_41255.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_50560.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_161617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_92138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_131778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_67051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_110194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_234378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_11445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_77436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_230213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_11171.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_111579.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_64343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_245298.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_199148.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_49381.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_6357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_258472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_229731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_189181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_64638.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_252053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_29080.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_74796.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_83452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_106379.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_166619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_12170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_11709.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_248591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_88089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_82219.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_92646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_65876.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_91621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_248381.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_183383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_91243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_96728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_102496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_210975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_228109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_128632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_242437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_253773.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_26580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_144793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_162726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_238897.qa.bqv
