/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig45105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig249882.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig182104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17661.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10652.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185306.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig122715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138753.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20706.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig130620.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109841.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig216000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267356.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig175376.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig209072.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32148.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig179063.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239323.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig276422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75760.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133283.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30665.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig140507.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig240514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig124159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17917.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10678.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig177248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig253421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig134793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187197.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig96577.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig55712.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35678.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig231514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig234201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig242218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190956.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293939.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61009.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35337.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57164.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig140694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14022.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig97899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig240521.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra54.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170430.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig259985.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig274158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig258520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig172646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig148031.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185761.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21848.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig33355.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig273921.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72002.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig269760.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig201683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig59428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267424.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig66098.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210261.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig231647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig76297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig2254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149507.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig101977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53339.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12379.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig218706.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig194608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig259621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig222337.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig62106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238241.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig233073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig114815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38932.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6311.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig102865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig46880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig262521.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig179238.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig141908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig37655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig262685.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig141926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig196873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig80998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig247730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig247000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145905.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144658.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23706.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig107440.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig193203.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260381.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30564.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51022.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig236304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig269222.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig102325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig83608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig173719.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260162.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190306.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig245429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig197354.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20478.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50809.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig87684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig183314.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig166521.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig208517.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig33387.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210848.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig266643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig82553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20936.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig158060.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig198516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig207188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig137116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig183579.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig209575.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51701.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig272226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig67748.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig174997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70239.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig148622.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143333.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31863.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23810.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig110657.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig37382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71424.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig65394.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig177554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig166435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig88849.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig222928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig73644.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig270560.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig182926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig81752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig276516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280152.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig107599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig278314.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig219478.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig137698.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig176156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260091.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118699.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig268863.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig217924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig253192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig182898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig259567.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig254953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig79400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243379.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig252244.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig259755.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig263940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig225232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig100953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig180102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241753.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig261976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig206734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32100.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig183552.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig122937.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig65678.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig203196.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4414.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig121730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig93616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig219727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig137549.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig278323.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig214628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig203914.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32576.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig1986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig209796.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135914.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig166032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig289052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32215.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104379.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig139520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig248383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig55625.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig259966.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38939.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig33534.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184312.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig100758.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig92949.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig46969.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8930.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig276822.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig176610.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig252104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72353.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig272297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144945.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig172420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159654.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig112465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig52501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57967.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig122447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99191.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53948.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig173565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig234556.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig2164.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168559.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig287122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig272815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig277491.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig262947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig121789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig229502.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig102171.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284356.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig197633.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig93996.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246140.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig55006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75020.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig275644.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig277927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig68041.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig26260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig105617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig196158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19399.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235451.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig160013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig208707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig254837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig161720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig86231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239478.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig66056.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig110457.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig207326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig265588.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig101930.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38753.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig262110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22333.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109775.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig152823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig272568.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig100668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50054.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32239.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27347.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178564.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig216373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig94700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig124499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117355.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig181353.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig121330.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig193287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig45323.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig206903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199229.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig197057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig106350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig232599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig261200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig221149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54573.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig207753.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig83457.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig110085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41614.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39813.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132050.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223346.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7336.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig263618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113387.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig96353.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig63235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig167084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig64004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig175949.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig37449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig128672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig87235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig86170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279821.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21759.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51175.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig182596.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13589.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig157319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig136515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig160893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75719.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig110499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292080.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig242097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig234139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig63068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149323.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig114066.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig167631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig233832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117263.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189620.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118943.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig78565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig183970.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig121536.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig195608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig289182.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig183050.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117092.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig289237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig87072.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig291109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21658.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig174759.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig74300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig174299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig73823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig295074.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig141214.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22681.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119059.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig270128.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235817.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig207362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig182584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig158141.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283708.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig183260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig66217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig253160.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig174406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30650.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig207380.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig216150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig218619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig233822.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig262380.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig152928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244347.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244573.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16375.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig276371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168690.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7486.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig48445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig92001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17275.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99613.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig236109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig56201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40277.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig249992.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig74403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig211102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58733.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131148.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig163411.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186663.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig87257.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144821.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig295111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig107467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig232378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286962.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig211542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig91802.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig262324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig68618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig107361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig122136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig247628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig197406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189475.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13775.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig87875.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig176702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig229405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig93357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig123891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42005.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig123160.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75381.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig225047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig262482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223544.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267336.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig92116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig95679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig289881.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig240218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138936.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239427.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132956.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig127624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig211366.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig158242.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig175309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111658.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig174756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104769.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig224768.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig195774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig68591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra574.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig176569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig102450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig123537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig81033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig200596.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig60395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig245425.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279895.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57234.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig203963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig254558.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig249726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig89814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig105972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig179857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig179358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig198494.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig67405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig203820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig148405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35374.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig108481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213425.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig258334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig139499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig120696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288732.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125216.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292242.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig196051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig212166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185866.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103923.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig180640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15021.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig101584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig105390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig80784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig291382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184054.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig164046.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig270972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28438.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig139235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig182448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271491.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131042.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig251841.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig166952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig160283.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23956.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig255697.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71779.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27769.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig208499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36214.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18142.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig203423.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig139490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig64729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig261309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69638.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig93943.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig120113.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig180686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109654.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig181991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294292.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155431.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271760.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig287463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145922.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58961.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186961.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199748.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16648.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig87783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig198688.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig65018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22019.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig45812.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10133.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159687.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig248499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig252198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig232158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig160158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig152977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61780.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig129590.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig97036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99160.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig176777.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig64736.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig100564.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig289178.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig217785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188759.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig228116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12625.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig112880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190337.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig253778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig227093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig86671.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig120442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44340.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig252204.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig67032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig56497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig84668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig240522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294275.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig137579.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig203825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig74327.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig96566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig232882.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16348.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig179009.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig222629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig222127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig172845.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig88771.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig247580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig179621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig221737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig37118.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig112829.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155750.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig274985.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31541.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig83264.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50816.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220444.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig275161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra17.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118795.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig108486.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig73085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250074.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig182461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8829.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig151015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12077.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig181375.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig163838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig230518.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig49012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44374.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38120.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig221421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig212089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144861.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153577.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8863.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286521.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig269694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23407.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138042.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290433.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig92962.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig214177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig268662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig252640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig258190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig76825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32342.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223160.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28781.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig95246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293805.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig141720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig96622.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig209138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig247282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185466.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189241.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20742.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig89104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115492.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243466.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig177002.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig127649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig295285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig121512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223507.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig81855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig214070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig127864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146850.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig217322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13387.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig256236.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig60329.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig48555.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20901.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig128792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig55331.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig157842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19484.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig91587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig247276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig257450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig48805.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig98948.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9534.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig158101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig182480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig212393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig242479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig94036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig90350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig252615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178022.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig183655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig227903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig177528.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig255057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig65615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig77364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145119.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36755.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig151173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig64624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189763.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24943.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig175371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75714.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10394.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig211563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig82281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig127547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191340.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig121384.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12758.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig123718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6189.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig173886.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig66311.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig195254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig136324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig169849.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig83227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig80336.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig55014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig274492.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig129598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig48092.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41821.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig171603.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig77804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig193672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig176431.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig291965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig110948.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig66553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99641.qa.bqv
