/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_121366.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_233410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_117600.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_78437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_356654.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_197434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_352141.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_353112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_67223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_358468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_19112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_1875.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_379105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_225309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_75104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_21174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_201377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_232209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_207062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_247826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_277628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_248372.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_353858.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_204205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_304010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_45837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_297648.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_136408.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_38596.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_327925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_84328.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_220056.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_225561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_259521.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_36721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_296283.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_188493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_97533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_9548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_144815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_204420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_161774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_314493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_292181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_336688.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_199719.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_91465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_231668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_108147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_86808.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_202012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_179494.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_74615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_18828.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_359077.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_48902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_207704.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_49713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_378963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_192421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_344982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_298604.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_110455.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_353293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_43625.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_28393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_238182.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_254465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_247700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_211392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_183548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_331829.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_87797.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_312854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_299887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_285455.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_349513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_19925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_335652.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_102918.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_289801.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_183960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_4857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_3251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_48452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_138831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_15513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_277439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_349630.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_42218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_170094.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_160492.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_141964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_204377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_283935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_173452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_268615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_29515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_9419.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_265508.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_233477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_304723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_23009.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_19108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_285737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_122149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_311085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_98243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_337612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_69788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_172960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_47859.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_311354.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_272584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_273211.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_316659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_325402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_240461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_154979.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_201222.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_229690.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_163868.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_207042.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_279143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_158794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_321580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_177308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_348487.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_305493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_9834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_252846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_90782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_302342.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_312459.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_175993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_27402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_169598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_115065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_370135.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_175404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_204509.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_96987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_308435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_283282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_134301.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_367219.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_299489.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_103359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_149881.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_305749.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_313130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_272539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_186911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_68509.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_154769.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_96991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_161088.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_27919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_174051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_339892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_37212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_189029.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_103624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_275673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_376136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_12859.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_182943.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_147913.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_299653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_50029.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_34731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_284776.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_179990.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_243870.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_340948.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_185817.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_256357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_207761.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_282444.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_289175.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_185185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_194422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_56178.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_318751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_63877.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_206611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_220566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_211928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_232402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_270911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_63176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_114480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_37477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_188361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_186640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_116220.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_106453.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_113503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_89549.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_84480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_76319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_57902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_345110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_327142.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_199902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_266852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_348003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_249190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_188540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_326547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_331025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_173327.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_295590.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_177595.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_152571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_171617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_63173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_253990.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_108195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_216533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_3838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_154906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_100846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_241046.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_73475.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_227566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_274105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_335601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_79918.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_179483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_51302.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_373987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_55657.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_73848.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_150268.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_86705.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_78817.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_341834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_84385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_159014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_378917.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_294260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_318153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_348247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_221125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_112708.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_357594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_84463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_194584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_377703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_339697.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_130994.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_310897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_375378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_211853.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_262534.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_78015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_112045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_234724.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_231646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_43615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_225480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_331739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_248893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_56694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_307296.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_110680.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_204117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_295921.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_295811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_167937.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_296227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_39108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_308169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_70436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_320959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_20078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_368310.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_17284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_371310.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_81997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_86667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_184822.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_334143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_32261.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_159642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_182540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_198311.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_27067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_45818.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_377831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_54739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_344014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_335112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_196909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_140296.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_17841.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_211546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_58379.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_170765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_224914.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_23008.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_235655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_266969.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_293710.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_312205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_213067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_360413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_20667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_29864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_7533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_335963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_184386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_370620.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_197123.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_314123.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_290039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_132172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_77884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_2028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_375612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_272233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_217422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_54452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_9697.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_201081.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_44097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_374594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_19868.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_221324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_162804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_133603.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_171956.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_215986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_295129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_73940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_22163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_93676.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_123370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_40140.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_215447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_120629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_366212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_183950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_343765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_317818.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_168081.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_124782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_259961.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_370397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_261215.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_15870.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_21698.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_351258.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_129938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_249833.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_37782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_126254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_167934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_72706.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_154030.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_244465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_289233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_350319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_68597.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_261682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_246573.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_283429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_38283.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_171415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_171943.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_277554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_133188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_130799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_153076.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_219316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_307524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_103785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_9721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_186955.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_62823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_244295.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_105582.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_241518.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_200422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_26348.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_78064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_154797.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_43171.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_297633.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_213407.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_365037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_368209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_50572.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_320132.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_66678.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_170762.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_236891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_32101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_62498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_266789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_155212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_241915.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_84706.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_47153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_87553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_123975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_323538.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_327088.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_183935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_324461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_249743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_342268.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_111441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_230649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_163405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_122291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_13965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_27359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_332635.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_24359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_347338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_180436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_357408.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_183296.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_188900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_114314.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_202977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_311183.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_197587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_315233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_287739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_45964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_349239.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_31920.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_115329.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_359802.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_148526.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_63393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_319275.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_350077.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_156702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_346984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_49573.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_370979.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_268926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_189262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_111629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_220422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_188192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_202167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_347978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_348184.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_237067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_332807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_78820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_147876.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_66459.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_38989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_322914.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_77157.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_184509.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_264139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_276800.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_155989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_256824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_77445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_373229.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_125840.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_45991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_269634.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_201547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_193303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_208921.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_24242.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_77335.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_132592.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_336002.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_355423.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_244285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_25978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_303649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_25006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_207128.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_161004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_328646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_28043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_43780.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_143400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_244839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_94208.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_98552.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_143904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_76559.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_118303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_96448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_15398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_123905.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_103795.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_103615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_198431.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_290574.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_59280.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_114975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_183481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_36580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_57217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_206980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_114130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_309770.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_59509.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_117689.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_54806.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_49819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_7002.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_320667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_84951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_233706.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_36331.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_375882.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_300291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_50385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_288170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_268631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_142515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_188997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_8547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_44492.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_338716.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_22446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_148663.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_8147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_67838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_267154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_61185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_369341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_113505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_236535.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_34823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_160754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_275234.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_250443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_369158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_55470.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_34108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_151192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_33948.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_67146.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_240995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_41737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_93401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_219940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_343623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_329269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_122864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_251344.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_10528.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_264671.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_326115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_21385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_287148.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_20079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_255686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_276383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_7484.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_269653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_302287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_344752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_365241.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_338565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_256179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_160374.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_356236.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_292033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_362613.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_297095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_107623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_302796.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_102642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_139617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_306789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_243720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_303198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_311250.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_71341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_86125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_291384.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_138412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_371566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_119514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_166115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_313003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_69840.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_41140.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_265705.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_34335.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_264721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_317933.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_275960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_22694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_230861.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_379322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_361838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_169720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_5025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_286762.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_288598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_101041.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_227982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_57144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_269375.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_212151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_347027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_280083.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_174805.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_131164.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_361808.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_267529.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_147764.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_273026.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_58469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_250540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_181445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_185293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_306022.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_81794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_192392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_134847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_223297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_231608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_312023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_199832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_163752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_289423.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_96067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_346625.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_162430.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_163293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_320270.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_312406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_250361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_217600.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_159160.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_153656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_8091.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_247560.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_323085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_238996.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_249565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_270092.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_116218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_194789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_7292.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_175240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_226487.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_69768.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_266622.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_28112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_1348.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_32786.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_73646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_308618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_138945.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_174957.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_330533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_364401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_54882.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_35893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_191158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_66012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_336011.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_211410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_369585.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_237101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_241356.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_122768.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_365411.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_338397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_39670.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_304639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_77986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_282422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_347124.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_152058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_211353.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_171432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_367218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_233606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_376339.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_132260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_138476.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_91238.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_365202.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_219631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_264358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_186509.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_73346.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_47008.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_99040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_247732.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_23721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_2663.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_349722.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_88038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_352643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_331546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_254603.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_225424.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_305496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_328388.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_152168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_152891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_52392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_349519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_32675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_64299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_114207.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_235680.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_71859.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_285185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_268.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_110456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_191154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_217171.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_341491.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_101875.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_314511.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_152684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_339064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_215583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_317984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_32389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_200492.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_256310.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_71442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_225911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_298177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_378809.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_317837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_287050.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_146897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_246868.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_254550.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_178883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_50177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_334904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_138447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_21279.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_36219.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_91997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_262578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_297563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_282130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_103432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_339193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_54962.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_178384.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_28820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_99157.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_290967.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_111400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_370571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_36348.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_182522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_96426.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_140962.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_200821.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_268112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_7736.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_295982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_375289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_342403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_13341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_217309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_320207.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_335061.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_2515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_207849.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_217810.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_62719.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_175114.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_304709.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_332739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_254007.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_200617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_136679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_219720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_322577.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_38497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_76161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_189738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_123314.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_94635.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_4813.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_299471.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_66562.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_339615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_319793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_239746.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_174692.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_302601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_229832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_372632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_343172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_300334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_366413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_169001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_265647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_163696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_296360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_350617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_352606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_338931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_272300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_147073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_329142.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_171520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_339332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_184875.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_203090.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_166038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_52036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_27186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_362881.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_324320.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_127309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_358753.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_372322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_286293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_75846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_343187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_217028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_106135.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_105419.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_353005.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_209551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_7102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_168494.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_42857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_140240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_79263.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_356938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_52220.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_146643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_146439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_375590.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_225446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_57358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_197363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_184397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_117200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_211129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_328881.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_49211.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_257326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_25880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_266385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_203056.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_220443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_163144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_150091.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_258326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_84172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_5908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_16670.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_375329.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_52583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_363873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_272219.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_61178.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_244694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_377031.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_61992.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_190503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_334952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_265373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_185824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_258310.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_35559.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_68207.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_99535.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_190174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_120437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_333603.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_169596.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_152163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_135778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_46521.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_168412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_74447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_136981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_329398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_43513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_162903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_77926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_186392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_237695.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_128690.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_368254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_325359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_195346.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_259416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_111995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_203481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_79281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_345907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_296954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_156981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_137860.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_255632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_253928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_3623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_296055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_167659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_266212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_175177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_35721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_37808.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_150101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_356316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_5642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_186126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_364013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_169798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_37115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_277025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_199884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_196297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_45764.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_322368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_144679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_56370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_202019.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_209895.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_229131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_215730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_356477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_49339.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_199097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_338810.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_202519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_204683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_130585.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_244472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_165410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_290893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_62239.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_273176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_58979.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_94347.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_260259.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_259946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_234961.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_157136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_155132.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_150551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_329621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_276495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_328979.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_174812.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_316333.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_344815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_159818.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_243960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_250062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_54570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_344959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_324989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_113646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_22802.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_239494.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_61637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_379325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_226668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_151299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_331493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_299004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_283894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_341081.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_254430.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_292221.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_156978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_106070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_261378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_244526.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_350550.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_366977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_283111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_69358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_216223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_95741.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_269900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_376628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_155835.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_323926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_69196.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_252469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_13265.qa.bqv
