/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_223735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_211794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_115341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_49549.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_218552.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_123804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_134047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_207829.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_202842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_54322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_26176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_134929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_71137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_249543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_85462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_82401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_22124.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_40525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_249949.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_187971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_105134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_240075.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_152851.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_102395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_122319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_245130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_69313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_227605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_244488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_12717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_30706.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_83946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_170452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_116414.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_8735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_175257.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_212929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_227761.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_254516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_79278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_207456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_177468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_80693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_121778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_70392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_110095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_210654.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_21664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_218696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_251417.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_103954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_246678.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_75628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_119358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_111615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_60039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_195819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_237865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_224963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_195986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_150103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_48377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_133739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_144274.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_212605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_125156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_175290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_112360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_20943.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_115463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_205693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_30079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_139767.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_238939.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_198942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_242394.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_99256.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_247570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_245930.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_149729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_232619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_20333.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_28586.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_203325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_20035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_113592.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_209318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_260463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_105729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_69304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_34890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_106276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_125951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_81334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_105896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_99977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_159159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_64235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_38586.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_118822.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_143037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_204706.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_80255.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_74477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_45430.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_198660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_110064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_160371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_99370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_231397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_81481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_49891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_21469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_43300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_54388.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_220682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_136077.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_107718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_247270.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32886.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_143490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_17426.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_155237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_12891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_258411.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_163935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_259289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_106428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_29495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_75667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_43824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_137760.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_181167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_141689.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_30599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241030.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_143403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_150176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_236508.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206369.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_185712.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_83893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_209889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_222368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_10338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_221084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_250840.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_202478.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_230647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_22480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_30960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_239124.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_181472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_131006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_86408.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_147448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_51076.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_137542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_144363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_197934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_82911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_1927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_261798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_251365.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_99273.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_76148.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_22363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_70739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_13949.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_218531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_166073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_13846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_125353.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_90703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_80820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_202291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_50931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_120354.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_18725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_64926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_26193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_8226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179355.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_64006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_148828.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_242634.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_2427.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_216900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_126617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_246466.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_231496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_247780.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_223693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_43963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_106446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_106230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_198655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_2251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_198403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_90715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_129210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_87130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_77667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_24437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_28659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_198079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_229359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_112797.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_166908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_225367.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_118997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_136404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_117975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_159540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_93893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_27336.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_226123.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_231857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_164554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_101201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_63401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_97520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_173369.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_36409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_43515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_127842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_26657.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_254111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_99847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_16363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_46115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_52315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_194245.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_259385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_77400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206094.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_215112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_139519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_226249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_4738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_158986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_62737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_130857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_108744.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_60944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_195409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_202885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_26900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_136628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_5674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_139685.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_222580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_143207.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_22666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_72855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_177141.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_99051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_91681.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_177937.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_55391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_239345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_59257.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_27772.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_253580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_238344.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_109482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_127301.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_120203.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_198774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_250369.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_48977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_93525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_2637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_149899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_123963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_140786.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_11439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_237894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_22015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_180565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_260059.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_106186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_249968.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_47665.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_105477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_249791.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_175653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_82383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_202883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_174162.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_198443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_151088.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_140069.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_88073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_227458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_197309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_221350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_17424.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219762.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_50754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_163077.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_29024.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_197623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_64245.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_18824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_176496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219526.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_28230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_233473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_231555.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_105452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_222920.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_122481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_258377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_196869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_30056.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_257008.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_43437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_126012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_88417.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_254337.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_213185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_120467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_4153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_129599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_112377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_124228.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_103727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_6996.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_96828.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_42016.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_228059.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_156283.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_75063.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_132898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_187935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_55889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_62546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_253821.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_45237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_152693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_44155.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_188645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_29721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_50161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_186732.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_161596.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_114298.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_160521.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_205783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_200944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_190551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_43404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_145125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_56283.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_145539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_3938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_78919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_74915.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_236936.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_121186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_117177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_39721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_252569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_243084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_40402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_10476.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_213635.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_74313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_116089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_110520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_232655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_57351.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_259078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_144594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_135701.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_232362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_197999.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_246715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_1317.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_218662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_128905.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_197800.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_67982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_104608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_85624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_167123.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_134856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_44815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_31334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_10907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_255506.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_11168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_131402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_196621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_15664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_108858.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_6726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_24588.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_11468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_216410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_23364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_12409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_6606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_158362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_103454.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_115641.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_214280.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_248682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_5726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_38232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_29237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_11889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_106582.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_249689.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_72841.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_91288.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_100726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_152830.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_114785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_161583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_177701.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_3819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_187512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_201079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_209372.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_108734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_62395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_74863.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_155834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_54659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_107921.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_70035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_239595.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_94444.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_78807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_61767.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_186485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_58831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_45629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_56919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_150286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_139068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_102890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_105107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_85459.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_171565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_200637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_64823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_3690.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_1485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_259459.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179258.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_86969.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_71187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_181286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_135087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_169558.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_33822.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_90377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_151227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_182693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_109967.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_216707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_36883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_166798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_88801.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_42136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_189425.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_48846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_231942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_149209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_193779.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_137798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_55083.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_82728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_35838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_251718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_31015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_225186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_27734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_16169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_211925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_16261.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_198955.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_155808.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_148948.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_202856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_203197.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_102235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_40987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_205893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_246543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_143440.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_191441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_58274.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_261432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_127765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_70726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_221552.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_231885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_121179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_6874.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_61433.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_41539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_87347.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206261.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_24972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_120687.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_191940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_65621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_157981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_243285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_236665.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_90047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_71114.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_102048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_168021.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_245301.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_8888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_243904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_48203.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_113517.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_27422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_75195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_116876.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_75023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_246735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_47711.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_125750.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_233429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_40191.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_142503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_210783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_29684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_117935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_194478.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_59115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_123411.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_170497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_190297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217574.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_244669.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_212202.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_91254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_143248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_160640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_118793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_103717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_246287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_31668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_102471.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_61985.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_6580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_202672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_191765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217970.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_102651.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_235303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_254662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_97924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_243550.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_4663.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_244653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_257587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_203616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_57425.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_165811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_54162.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_17458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_117494.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_68929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_129047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_100121.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_161730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_196928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_149506.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_82929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_220211.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_172723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_209727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_20860.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_39584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_7679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_71390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_126248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_58865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_218553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_248981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_81016.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_250452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_21747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_111593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_191978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_225092.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_14228.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_91188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_132994.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_109178.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_213144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_229043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_236082.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_86248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_22292.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_126751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_43197.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_261403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_118449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_53809.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_62398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_193867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_82473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_195646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_121512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_180470.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_21026.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_49130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_198485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_35227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_142620.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_141409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_132081.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_8925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_61867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_56805.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_109057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_67846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_224703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_142003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_4204.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_18071.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_96451.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_104448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_214885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_109405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_229874.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_173291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_20404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_98745.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_240514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_85013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_94102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_190606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_101591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_174138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_155292.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_142014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_236629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_216718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_203069.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_251278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_8341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_173554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_76904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_258505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_254754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_195673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_10857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_228745.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_7730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_118912.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_225777.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_53995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_178188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_196360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_193112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_166630.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_170289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_182177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_9505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_133976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_105252.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_76765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_246102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206771.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_209847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_15935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_47888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_59756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_135838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_220117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_1395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_188888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_182301.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_148773.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_10966.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_9078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_11307.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_113614.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_89884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_218329.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184764.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_114485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_11968.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256828.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_187493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_93500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_3461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_132389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_19740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_200573.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_240343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_224902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_242660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_159352.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_197491.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_26038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_135247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_186594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_224237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_245590.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_146979.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_110017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_141814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_10022.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_107582.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_213931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_144355.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_137885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_56172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_43056.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_178582.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_234149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_87329.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_154239.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_185186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_110469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_79260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_175990.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_69544.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_216503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_39530.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_150531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_244801.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_112343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_73211.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_67253.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_64449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_98220.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_11256.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_171923.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_139251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_54738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_212794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_59031.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_80428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_242272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_20700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_189169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_64179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_13269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_94914.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_86910.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_53871.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_28898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_38342.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_181121.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_50439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_88083.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_28045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_158869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_98075.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_82835.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_117279.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_5735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_46252.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_183406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_192247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_31232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_132983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_135408.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_36282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_247265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_258011.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_210248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_199068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_229700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_64927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_230303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_44513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_39368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_151866.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_235248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_92274.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_63939.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_102323.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_199594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_147289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_232792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_79359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_36737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_31172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_231147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_85416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_34362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_79625.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_159768.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_2545.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_212896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_114073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_201697.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_171014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_138541.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_37292.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_107123.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184949.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_13387.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_172150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_189570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_122751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_183338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_1004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_59282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_247616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_202717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_172629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_150723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_235087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_172289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_203792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_76491.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_148028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_106621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25641.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_122516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_161195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_51649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_77971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_94173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_234792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_30314.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_209238.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_242343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_11403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_175282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_70512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_46251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_89338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_130674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_22443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_123248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_240500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_244413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_14339.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_113952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_67004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256219.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_90020.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_108153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_229283.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_155799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_147049.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_239492.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_222715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_237582.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_211804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_239593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_120087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_163884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_196510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_113798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241841.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_125549.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_185498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_7279.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_228943.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32487.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_254441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_24888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_86012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_152129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_246858.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_132275.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_153726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_210710.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_97179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_200516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_218646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_34967.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_247371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_69595.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_257169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_147167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_14906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_40260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_139667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_90173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_18814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_98511.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_89908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_106233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_113294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_153924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_31950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_65791.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_248532.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_39443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_18790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_119601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_86465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_178468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_164852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_71198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_50260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_123075.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_58659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_12151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_18530.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_28001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_185563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_124534.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_53041.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_91972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_96609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_177406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_132072.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_169677.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_183153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_255205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_234090.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_64902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_207879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206384.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_108514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_140534.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_26778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_131449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_58869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_47968.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_177951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_22706.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_230986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_35131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_136853.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_73217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_101052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_12015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_38037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_9322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_53165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_78391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_169304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_105502.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_89955.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_49160.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_1612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_75956.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_191508.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_215044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_43156.qa.bqv
