/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_34980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_115207.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_28490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_69867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_181793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_84159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68470.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_46225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_188373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107031.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_163172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144772.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_83203.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_104272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_18888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192922.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6320.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_191286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_200093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105175.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_200118.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_126279.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93426.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204555.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135204.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_82618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108813.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_69907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_47209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_188019.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_131075.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17973.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_156549.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42592.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_56927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_173903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39704.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_59374.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_69810.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_19927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_205215.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_153262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_208913.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114374.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_7396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91489.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192701.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44913.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_73816.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_169097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_201939.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_176536.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170074.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_50427.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144821.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_71899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44691.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77878.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_83523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_46176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_67986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121346.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_151313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154008.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_37548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_201674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199697.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_188533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88719.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_34344.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_41735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189091.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_190616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_130087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_54762.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_151086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_141305.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_183482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105090.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_185619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_61249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_50656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135762.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_40787.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207049.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_156232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_119708.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178641.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_104359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206007.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_205523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_113468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146022.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_47409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_81584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195372.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_156673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_82179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_168223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211072.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_168236.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_165645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_90637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_83573.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_41270.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_23601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3228.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210625.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30258.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_40171.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_215910.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_122172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101699.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79568.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_200640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_90011.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_205420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198267.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12990.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182803.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44381.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_194300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120586.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206263.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_41786.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_9569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38661.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_43186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149440.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212755.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186676.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_111184.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_160510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_76057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17353.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_66364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_100216.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_141702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_194877.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_18184.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70827.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_73662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149853.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_71197.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68379.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_115790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_5182.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12741.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_15128.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_127739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_171552.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_112222.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99476.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_23283.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179808.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_46621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134250.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136228.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_145735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159380.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148489.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_66247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_113492.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178874.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39528.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_191896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11559.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53344.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_81417.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_18500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_126554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195029.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_15923.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_152775.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_141643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174484.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_54601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_203475.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13076.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45597.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_215523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_15118.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_169838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192128.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27080.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_100772.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_160719.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_63728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_201174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_15336.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_191339.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_191926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_66048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_128883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137581.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_151624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_181800.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123932.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_47624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74453.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_43722.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_119778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_90231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_156284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_76103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32302.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88528.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_184200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_130515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_51904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102296.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_56552.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75295.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159457.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216098.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_113222.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_66763.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_151809.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_151225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_9023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_126157.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133470.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_18850.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_81567.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48882.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_127547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_67174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_10093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_76078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_215634.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20279.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134216.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_104957.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_92878.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_23250.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_18043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8937.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216708.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_167345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_115341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49549.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207829.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_54322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_71137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_82401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22124.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_40525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_152851.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_122319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_69313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30706.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_83946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116414.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175257.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210654.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_103954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_119358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_111615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_60039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_150103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144274.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_125156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_112360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20943.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_115463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_205693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_139767.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99256.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20333.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_28586.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_203325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_113592.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_69304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_34890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_125951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_81334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_64235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38586.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118822.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204706.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80255.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45430.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_160371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_81481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_43300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_54388.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136077.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32886.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17426.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_163935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_43824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137760.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_181167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_141689.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_150176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206369.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_185712.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_83893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_10338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202478.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_181472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_131006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86408.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_147448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_51076.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_82911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99273.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_76148.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13949.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_125353.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_90703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_50931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120354.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_18725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_64926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179355.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_64006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148828.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2427.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_126617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_43963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_90715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_28659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_112797.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27336.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_164554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_63401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_173369.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_43515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_127842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26657.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_46115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_52315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_194245.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206094.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_215112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_139519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_4738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_62737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_130857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108744.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_60944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_5674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_139685.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143207.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_72855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177141.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91681.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177937.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_59257.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27772.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_127301.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120203.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_140786.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_180565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_47665.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_82383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174162.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_151088.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_140069.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17424.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_50754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_163077.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29024.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_64245.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_18824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_176496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_28230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_122481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30056.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_43437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_126012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88417.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_4153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_112377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_124228.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_103727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6996.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_66391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96828.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42016.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_156283.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75063.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_184857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_62546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_152693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44155.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_188645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_50161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186732.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161596.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114298.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_160521.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_205783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_200944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_190551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_43404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_145125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_56283.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_145539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_78919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74915.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_40402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_10476.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213635.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57351.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135701.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197999.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1317.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_128905.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_184045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197800.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_67982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_104608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_167123.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_31334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_10907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_131402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_15664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108858.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24588.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_23364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_103454.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_115641.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_214280.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_5726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106582.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_72841.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91288.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_100726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_152830.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_184004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177701.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_201079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209372.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_62395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74863.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_54659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107921.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94444.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_78807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_61767.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_56919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_150286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_139068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85459.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_171565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_200637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_64823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3690.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179258.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86969.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_71187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_181286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_169558.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_33822.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_90377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_151227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109967.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88801.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189425.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193779.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55083.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_82728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_31015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16261.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198955.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155808.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148948.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_203197.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_40987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_205893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143440.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_191441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58274.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_127765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6874.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_61433.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_41539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87347.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206261.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120687.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_191940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_65621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_90047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_71114.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_168021.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48203.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_113517.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116876.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_47711.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_125750.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_40191.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_194478.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_59115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123411.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_190297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_217574.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212202.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_160640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_103717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_31668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102471.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_61985.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_191765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102651.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_4663.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_203616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57425.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_165811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_54162.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117494.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_100121.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149506.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_82929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_172723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20860.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_7679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_71390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_126248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_81016.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_111593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_191978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_14228.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_66900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132994.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109178.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22292.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_126751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_43197.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53809.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_62398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_82473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_180470.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21026.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142620.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_141409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132081.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_61867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_56805.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_66998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_67846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_4204.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_18071.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96451.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_104448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_214885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_66785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_173291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98745.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_190606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155292.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_203069.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_173554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_76904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_10857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_7730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118912.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166630.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_9505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105252.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_76765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206771.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_15935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_47888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_59756.qa.bqv
