/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_201846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_5037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_6838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_159082.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_173650.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_20292.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_135599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_150718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_194167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_60545.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_162035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_95060.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_28627.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_87831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_50109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_84115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_138534.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_14725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_201647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_157635.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_133982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_45395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_159517.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_84358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_72326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_83065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_235801.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_128551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_31946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_2355.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32331.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_226551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_14294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32699.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_105726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_236088.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_230906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_117172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_29390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_133104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_208287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_189342.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_166950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184072.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_82246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_103211.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_171272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_69836.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_175378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_92598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_147903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_123829.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_112133.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_166273.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_211115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_137844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184221.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_178208.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_59537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_131276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_69647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_231603.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_126531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_95790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_84129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_214991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_226482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_62197.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_177675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206202.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66121.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_124220.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_23522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_190108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_21662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_150413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_122168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_151359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_166502.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_205591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_99118.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_108902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_89598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_34014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_231895.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_97958.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_238381.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_144773.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_171495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_89157.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_157378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_258881.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_111940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_2686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_53600.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_114826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_201037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_41868.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_97091.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_150872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_182166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_245784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_110590.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_174775.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_229602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_143728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_40626.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_198935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_65498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_13086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_112703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_176784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_29625.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_261754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_33722.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_3939.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_259579.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_100038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_213205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_135209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_175294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_100558.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_147730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_163903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_117132.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_208531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_154473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_189433.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_96018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_72173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_13894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_144169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_146259.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_105389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_177832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_135082.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_231158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_48075.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_84337.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_134125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_15027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_87683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_70335.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_259252.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_116436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_55966.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_192487.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_215676.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_253514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_68807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_7702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_5322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_127643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_58745.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_7563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_92356.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_125089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_259162.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_167769.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_39130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_7778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_19503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_210282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_47741.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_246752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256708.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_144529.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_197515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_196923.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_130754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_119449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_100238.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_186450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_156976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_134449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_125418.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_112541.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_222398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_114041.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_259892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_129716.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_162243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_250294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_55076.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_159791.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_139136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_244910.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_18142.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_102454.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_67820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_208625.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_248956.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_52560.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_237887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_183673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_233749.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_119209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_96421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_13748.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_260556.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_114957.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_192992.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_161541.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_175865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_101093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_23516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_223170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_41245.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_60264.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_19555.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_119338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_24950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_191410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_7260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_251358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_169832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_207269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_252107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_10524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_205458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_192200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_90581.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_97767.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_142865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_212752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_218015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_44909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_22695.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_70882.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_190543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_167499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_224185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_92122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_115070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_109136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_183974.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_24796.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_51594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_160500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_190752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_214875.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_106062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_202441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_74873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_259987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_54896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_120133.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_79631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_52778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_230693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_229234.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241776.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_59548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_80989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_145937.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_159272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_146972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_72885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217597.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_7843.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_156783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_188027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_15461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_41067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_10510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_231108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_143618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217050.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_83738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_90833.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_27006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_224807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_89619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_260936.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_57058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_95085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_52608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_92200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_17924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_175275.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_150403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_65531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_137749.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_233199.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_117650.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_192090.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_246123.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_101844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_62010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_38643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_208325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_97953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_194261.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_134176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_51989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_148.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_155097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_96778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_105650.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_56524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_85607.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_41334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_157166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_79957.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_240845.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_162602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_213857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_117450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_195606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_254501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_201753.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_109885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_200320.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_18931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_16547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_78260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_124005.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_258214.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_158180.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_255817.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_67553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_143113.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_165414.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_187881.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_127041.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_70060.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_121245.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_40086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_135433.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_240804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_177172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_251925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_102648.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_12591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_195723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_51346.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_156541.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_36294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_99630.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_26606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_199726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_6343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_22563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_216777.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_132339.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_232219.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_2593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241376.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_143358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_67873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_215726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_156058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_140664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_62429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_37258.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_68442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_222164.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_224095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_101383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_21921.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_125369.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_131566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_205094.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_27528.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_119836.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_65385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_189479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_165855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_39335.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_239321.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_215331.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_164233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_214195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_230357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_248882.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_108576.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_99265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_19424.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_43087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_23442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_20831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_121169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_246003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_72602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_239896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_195138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_136800.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_97622.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_116909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_149785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_218138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_257543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_113576.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_8614.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_55530.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_157807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_185667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256770.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_76173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_187715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_85166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_157077.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_146014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_181434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_135489.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_141101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_18995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_183010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_42113.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_209987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256769.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_111636.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_93529.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_101511.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_253834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_139826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_54273.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_127082.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_195605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_13526.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_51074.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_255839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_54887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_261493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_139490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_167448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_171751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_109427.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_56458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_251563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_24984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_92424.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_133111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_238799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_173370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_63128.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_237185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_76684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_237777.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_227953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_225024.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_128640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_235123.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_146680.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_149173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_119783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_12682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_186837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_253771.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_46601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_123878.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_170707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_253475.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_162541.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_183377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_35028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_39343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_145509.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_135352.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_202756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_95059.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_8313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_216434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_248337.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_31789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66936.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_145356.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_146650.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_132247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_260093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_133046.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_155991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_226184.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_202282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_15648.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_14472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_54891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_226780.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_15340.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_35321.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_73723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_83465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_192272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_47765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_51852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_113095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_185232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_33641.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256119.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_214798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_47847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_88611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_114717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_97130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_24033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_192294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_139601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_202646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_4410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_72048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_90065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_119733.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_53366.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_208866.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_24664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_245702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_236039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_1019.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_77256.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_247319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_46109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_132888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_35144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_17427.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_80258.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_190039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_20046.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_51834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_123218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_20313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_145318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_75115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_172451.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_193786.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_1442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_191352.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_103016.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_198713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_190386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_195985.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_230640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_192829.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_162053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_15031.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_166610.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_212351.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_16049.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_178312.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_53614.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_111666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_6692.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_128418.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_207955.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_17465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_18971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_253683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_230491.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_62355.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_36992.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_31309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_163244.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_187877.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_58826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_86982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_28743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_68562.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_189415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_162168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_37227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_37221.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_14501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_99005.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_132225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_165231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_189832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_72406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_45129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_144940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_9174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_253907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_178182.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_119295.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_137678.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_85404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_132569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_127602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_140546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_127286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_154986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_74605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_198146.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_78775.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_260722.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_51278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_193630.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_93176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_60189.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_55686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_195643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_24133.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_113768.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_257403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_9133.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_46395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_223302.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_255499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_79039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_117484.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_171477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_109869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256120.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_31834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_108716.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_35267.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_148612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_193544.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_247033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_213912.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_171849.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_48190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_172885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_125786.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_17937.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_187988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_115611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_133645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_209251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_165067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_63400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_113748.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_206188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_199334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_182210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_51862.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_160453.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_11187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_174878.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_134209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_258946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_232685.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_30998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_4540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_194430.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_126612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_1364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_60946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_95986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_164809.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_225109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_41246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_88717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_19254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_52337.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_185631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_31690.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_6041.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_256534.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_15946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_185857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_6153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_171190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_134984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_187540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_112653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_34448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_255968.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_148261.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_163967.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_135176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_168940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_127239.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_204915.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_198173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_73728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_57883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_6013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_209839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_140174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_121903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_23157.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_14322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_76984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_172443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_163106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_52839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_27024.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_76002.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_111167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_142248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_79142.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_60587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_158704.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_218958.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_183396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_34643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_127397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_257655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_141489.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_96130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_143812.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_147468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_17360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_84017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_92011.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_212682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_170616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_69984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_162358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_208561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_105048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_242226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_205760.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_194506.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_77611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_51320.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_224575.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_45251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_67260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_207942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_213759.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_53570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_196295.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_243790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_196186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_227279.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_245349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_223203.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_111848.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_152062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_253952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_191771.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_55057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_128858.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_237359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_130099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_135759.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_202780.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_168513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_158102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_84741.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_147225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_93973.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_54611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_207928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_188574.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_234686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_85610.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_151787.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_230736.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_22542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_39073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_28877.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_116364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_13516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_198643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_211408.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_215304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_107201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_120160.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_35640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_41000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_99120.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_51403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_94183.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_37595.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_50665.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_74355.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_60155.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_146275.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_165142.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_261183.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_252655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_192686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_91054.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_236959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_7733.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_18044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_30847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_96006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_165823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_13904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_185899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_130884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_211733.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_102864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_164422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_212396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_187069.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_75595.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_171393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_139126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_101819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_89473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_193900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_42637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_211864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_143880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_125893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_128979.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184222.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_179068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_41653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_107651.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_15964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_210979.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_80883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_183988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_28884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_221606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_158850.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_166737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_72371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_249395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_124628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_171567.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_180413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_167538.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_160860.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_254158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_199451.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_250793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_185014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_49570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_119874.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_171472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_8362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_53266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_196453.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_196498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_222674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_145759.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_181661.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_227023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_8556.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32327.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_219452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_258504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_72901.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_72028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_81380.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_2034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_191742.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_63413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_152266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_102821.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_138181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_69107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_118817.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_129079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_122847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_247045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_232388.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184636.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_156110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_78961.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_181458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_80525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_235177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_101585.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_154946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_80825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_56766.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_180194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_184028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_226726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_71351.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_192165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_71334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_204361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_186860.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_132380.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_56960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241367.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_71949.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_128674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_188600.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_45229.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_143382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_203365.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_161045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_84922.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_103779.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_205864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_152975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_124227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_94160.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_258965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_139894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_245794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_218713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_68790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_60773.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_245118.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_25721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_258456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_82364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_142008.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_96858.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_149103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_17553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_45638.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_116703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_109807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_201774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_83426.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_189851.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_95483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_80291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_236500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_32782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_251824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_209863.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_247664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_249760.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_137364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_79628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_117754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_223661.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_221666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_7229.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_85860.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_39735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_209391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_175677.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_44400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_108194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_205329.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_246004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_16843.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_45995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_120516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_238023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_172092.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_215896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_138450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_241628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_234473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_138066.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_217172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_28359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_43385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_85149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_59647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_141855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_97591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_190826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_77921.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_234771.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_143729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_226802.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_111939.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_257097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_163986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_64284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_8108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_130666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_210987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_112330.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_120900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_94787.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_1308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_142951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_121042.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_154736.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_63200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_111575.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_85738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_18773.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_124734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_215607.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_107472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_66326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/sorAra1/quality_scores/scaffold_255637.qa.bqv
