/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_148008.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_283562.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_110907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_263698.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_200662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_135192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_190099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_267218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_35253.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_256140.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_196776.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_205404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_43838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_180226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_227675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_105677.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_15911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_39995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_293224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_155060.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_108390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_54243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_186891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_193993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_185249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_299359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_226219.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_249637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_312806.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_127476.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_297788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_308936.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_309135.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_257772.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_41096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_120391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_7188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_232108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_46942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_138642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_90137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_205803.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_215027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_261031.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_207079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_152477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_22814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_136690.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_226077.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_304482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_73622.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_208177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_163374.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_206931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_190549.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_85391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_119391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_260883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_320010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_252463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_218098.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_80894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_24092.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_215652.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_56376.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_193723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_233776.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_259164.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_271835.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_285254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_29790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_244034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_218169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_317589.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_90838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_11763.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_249308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_7703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_286323.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_218044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_252848.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_96993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_196410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_261521.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_106010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_87279.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_84194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_180306.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_210206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_29003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_89213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_24559.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_72658.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_179145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_238294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_252909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_118691.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_161030.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_74231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_152566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_285964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_215975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_244154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_58873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_274763.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_45854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_277589.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_159295.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_308300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_138153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_206327.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_122750.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_103030.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_156171.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_138926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_134479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_175170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_54207.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_264140.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_134913.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_241672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_261329.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_65935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_2602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_268807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_75498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_139056.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_166969.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_310206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_317224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_310925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_304462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_101417.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_133308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_197198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_130307.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_226633.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_11569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_45474.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_288963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_309138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_128360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_137130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_80361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_174223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_144605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_161244.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_112531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_189569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_320893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_166468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_191340.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_110802.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_252312.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_76773.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_153810.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_297144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_153243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_73778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_299618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_269881.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_193394.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_101275.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_133423.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_92410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_217006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_149089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_123513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_253526.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_223570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_205622.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_189821.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_33846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_198387.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_164817.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_142178.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_13373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_155949.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_23751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_185512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_150525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_136127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_166883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_263537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_147051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_267088.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_304917.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_160667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_60510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_218382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_285202.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_103215.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_223507.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_261540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_113667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_304090.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_303744.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_47057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_41908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_78672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_234994.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_75803.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_167601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_123150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_78396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_197066.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_11266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_159220.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_153545.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_80644.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_301130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_25434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_27055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_1127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_254176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_70360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_58512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_233651.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_277754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_230819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_112380.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_202719.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_82628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_7812.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_106984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_319065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_235557.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_64199.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_126111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_255920.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_80544.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_3011.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_171094.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_88588.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_103937.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_41962.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_282519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_93758.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_203788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_62306.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_167986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_81601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_302193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_234726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_179468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_54020.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_313865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_214463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_36837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_95619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_266942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_318855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_71759.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_136260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_156582.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_89172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_255870.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_127960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_100730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_249117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_230494.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_112536.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_135390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_37659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_1895.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_182643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_278733.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_318711.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_73269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_146099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_290894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_318289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_273101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_7064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_210115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_199694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_309486.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_253890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_235587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_218410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_154117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_131129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_53793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_233998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_226926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_143404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_292738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_314320.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_257879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_246403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_164941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_142373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_302268.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_102548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_227085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_267659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_158450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_76419.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_324220.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_211050.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_177174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_203202.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_105998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_116896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_206397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_238585.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_189125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_275565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_138387.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_223493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_225695.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_195357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_324178.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_46599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_231533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_81679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_117087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_276873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_73797.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_237238.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_150270.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_285317.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_169776.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_310012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_195267.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_29018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_203561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_309926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_276111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_134138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_321844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_84449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_14415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_175014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_1975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_205616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_67357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_190227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_127525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_143841.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_75455.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_227193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_253221.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_74344.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_53547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_39218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_51588.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_269272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_246505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_120554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_103618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_80585.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_258869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_282546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_181839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_163299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_156747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_322967.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_171442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_42737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_295909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_140020.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_276502.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_231542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_249710.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_320986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_103229.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_26835.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_28210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_204040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_233349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_192451.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_173363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_111563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_2644.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_99082.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_137728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_263246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_271291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_325385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_240482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_202949.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_78923.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_242849.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_75118.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_198672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_231249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_70044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_275434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_294973.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_91152.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_157202.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_67015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_177283.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_243297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_38114.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_19964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_82534.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_52535.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_217895.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_22631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_316250.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_71935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_58420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_298210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_170645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_67720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_31148.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_273369.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_200055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_259145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_232238.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_52718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_256764.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_55330.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_163666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_78925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_187890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_183472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_62714.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_274804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_36306.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_139709.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_174630.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_266403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_128825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_65785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_321099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_241304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_284073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_70831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_190814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_17040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_3549.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_106308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_193456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_16043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_207000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_278531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_39427.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_151838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_221165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_94267.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_218817.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_168586.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_23597.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_111341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_114501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_111525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_125583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_312272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_73271.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_164688.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_103757.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_199880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_303164.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_316558.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_185423.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_254742.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_220025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_288073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_264099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_215510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_110316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_101598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_96389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_122300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_89751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_182019.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_320059.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_2569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_149322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_249091.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_216571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_23602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_231702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_93872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_82290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_253503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_280906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_31963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_247803.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_10790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_75872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_82254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_67936.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_60367.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_271047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_267349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_171359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_58150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_131301.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_79528.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_31400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_128129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_253843.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_59588.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_144650.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_183807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_281270.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_111326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_303934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_79053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_247121.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_25084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_39606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_210356.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_164620.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_294668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_100894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_30964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_285698.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_46814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_287395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_22866.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_189605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_106842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_316759.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_56632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_168205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_71349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_230403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_133962.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_299490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_20686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_29469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_77589.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_80837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_44319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_168234.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_131898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_18273.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_233174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_41723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_256469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_241033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_116524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_50786.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_91575.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_48741.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_70034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_295193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_251149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_118079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_129239.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_322297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_234471.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_189044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_158621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_295568.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_307499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_9326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_59449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_47314.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_276747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_1674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_206473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_145632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_156606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_291271.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_259012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_127965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_182141.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_227555.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_280894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_85473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_44265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_58636.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_31704.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_148742.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_256551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_66630.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_184163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_171754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_71315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_109305.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_286493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_143519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_195083.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_203781.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_283702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_159208.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_127434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_33309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_124278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_175744.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_257938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_264601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_66958.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_196789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_167483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_85699.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_324531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_19846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_278190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_266768.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_29146.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_52703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_1243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_236928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_90743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_268247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_156569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_234446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_244729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_50212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_259703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_256137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_14742.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_292038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_240185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_48480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_258054.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_273721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_269508.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_61376.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_7814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_320331.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_117326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_181385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_140736.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_256910.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_120110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_242747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_91116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_197840.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_250048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_107468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_41435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_100912.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_265322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_14539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_265173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_180218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_3517.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_66433.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_2262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_310391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_117707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_200604.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_172196.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_246319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_55452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_219396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_118637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_56911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_90675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_157837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_271306.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_239908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_214477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_101776.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_34478.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_101074.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_310783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_179772.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_270053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_291812.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_292140.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_225766.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_127371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_232725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_136286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_70008.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_125797.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_302.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_279291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_260902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_260951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_166234.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_222700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_131788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_37479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_227159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_21942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_118291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_119401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_1287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_259848.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_317145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_152095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_301817.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_133497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_107124.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_72416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_222022.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_270455.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_131382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_163519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_280995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_19489.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_306216.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_118726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_115384.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_59110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_37416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_313179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_206595.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_235599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_91634.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_1661.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_274074.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_36159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_22298.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_144708.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_277674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_295846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_179872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_182513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_255391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_185395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_186867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_199723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_217382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_211887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_78288.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_300345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_188329.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_179319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_160978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_293921.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_90101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_180095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_249649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_287356.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_32102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_223201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_101072.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_6429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_45041.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_241596.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_54831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_293584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_321721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_131580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_136966.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_270591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_212542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_92623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_129866.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_112711.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_161044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_143664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_230149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_315563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_318551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_142017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_215193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_13539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_49065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_150628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_158437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_245211.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_173374.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_283954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_113442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_286938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_292158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_148434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_46216.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_162442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_54832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_178833.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_48906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_251513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_310548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_3993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_263781.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_210845.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_312549.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_62316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_198399.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_43765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_290626.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_102872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_196867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_264929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_71618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_156890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_228120.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_6225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_88464.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_174287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_184852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_224010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_199799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_150609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_279703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_194786.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_290335.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_225649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_5775.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_177343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_142756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_131431.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_200578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_265205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_151832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_278496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_60725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_140988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_302855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_164179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_104037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_254055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_6666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_27742.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_230339.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_101208.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_47274.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_29792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_213347.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_147758.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_158252.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_176718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_155938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_62363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_172198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_249002.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_74736.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_21536.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_63743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_77514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_239495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_274131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_210190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_314746.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_162727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_229230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_271445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_315312.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_97189.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_178053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_165965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_149839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_154358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_159933.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_303236.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_283163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_33235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_210052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_19059.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_269947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_199728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_30076.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_175005.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_255115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_1199.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_129168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_88039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_227214.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_32244.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_111971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_204755.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_314914.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_269526.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_285779.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_85701.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_290319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_15389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_128999.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_208305.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_47340.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_305370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_322401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_251294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_105835.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_256871.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_261120.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_311922.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_90514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_234576.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_103997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_67347.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_187541.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_232327.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_7595.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_46488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_212878.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_221695.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_282458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_18832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_175834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_61660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_270798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_195228.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_253471.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_21390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_169365.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_23997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_140848.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_287351.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_197801.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_170768.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_119897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_106935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_245618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_106537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_94333.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_239900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_37103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_155881.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_182678.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_62350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_290369.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_1776.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_241423.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_133441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_144413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_94861.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_244492.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_298790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_13654.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_225143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_127856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_117437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_158713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_30310.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_35952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_228986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_270230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_101308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_168884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_118450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_275791.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_272210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_236771.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_150936.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_152773.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_301416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_271399.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_188718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_231310.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_54833.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_315304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_185156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_36216.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_248998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_116322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_119993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_103894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_187807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_131885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_3123.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_154105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_259093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_280485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_190708.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_227237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_183508.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_291731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_264104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_54868.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_4606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_206564.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_81672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_145170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_245532.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_268421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_324027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_263915.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_274913.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_208650.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_157178.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_228215.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_107566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_139821.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_98132.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_7999.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_126428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_284715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_87761.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_31105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_263188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_190397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_36419.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_247282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_147074.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_93483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_131201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_237895.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_112265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_57128.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_283292.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_20593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_238981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_260342.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_106140.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_140002.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_263048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_191794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_7233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_152116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_91478.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/echTel1/quality_scores/scaffold_67632.qa.bqv
