/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_46864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_375382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_121765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_353241.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_119127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_19688.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_194571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_280864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_225166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_126043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_167657.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_317508.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_278494.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_274927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_91742.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_107501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_9110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_190195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_31055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_242806.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_239637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_88687.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_352215.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_104899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_284300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_285012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_234753.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_232168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_366335.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_276319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_349272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_367704.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_217167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_332861.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_163097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_119068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_229757.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_353707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_156639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_72996.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_170529.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_132921.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_217276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_322658.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_339594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_77592.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_368585.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_220531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_72594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_3121.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_204426.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_73557.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_20828.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_193894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_153989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_45792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_47654.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_112187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_33172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_371496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_349969.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_202298.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_373884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_234366.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_216066.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_339446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_83010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_29058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_259501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_340401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_93109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_30095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_160443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_49368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_328814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_54987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_144892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_21615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_340023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_339402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_215915.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_66207.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_97406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_160954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_143095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_98675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_107498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_206917.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_371918.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_87840.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_320684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_241717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_48236.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_360406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_48386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_83001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_224759.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_5359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_337670.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_247963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_57705.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_40887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_28126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_308655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_64829.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_267963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_245186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_277158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_286417.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_5535.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_200095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_82956.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_217448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_64747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_297237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_105808.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_141358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_374237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_341017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_199364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_301173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_119472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_282239.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_31737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_237999.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_141510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_135801.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_29547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_46910.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_121468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_320144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_163392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_324209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_315469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_369973.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_56449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_357926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_178067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_206235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_338897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_218364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_196054.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_226670.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_301354.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_293804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_16572.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_54288.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_61045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_238402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_348513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_78558.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_342290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_177224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_302866.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_356351.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_178340.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_66393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_379427.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_8592.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_261808.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_265834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_130003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_317561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_26044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_363612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_271889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_121191.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_266665.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_325718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_26577.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_118428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_87670.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_288046.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_189131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_223135.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_284620.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_266894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_228537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_345231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_155696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_81210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_351286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_95932.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_101702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_259000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_316832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_375753.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_351370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_141447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_270656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_234165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_10560.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_369816.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_120617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_218308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_376848.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_151334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_46750.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_227429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_221137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_315654.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_294334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_205250.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_260773.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_240267.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_299286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_260735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_334138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_23879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_34300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_24849.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_296070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_264522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_216036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_132039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_314050.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_58001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_75575.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_360246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_193622.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_9285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_16244.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_177325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_130376.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_193366.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_338034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_114694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_81684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_146308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_112319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_154826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_107987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_7276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_203463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_343668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_176292.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_295135.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_291341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_74857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_368543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_309248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_326377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_6401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_303498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_25220.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_276896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_253281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_377898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_15515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_285852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_43583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_14218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_147411.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_170686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_318617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_228800.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_264757.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_234803.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_152415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_253427.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_378707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_33807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_213953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_49912.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_302617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_347837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_227235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_31243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_244793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_45851.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_18281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_339058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_96237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_318386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_278294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_107827.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_131522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_241208.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_261780.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_276391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_255217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_283733.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_131620.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_22281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_122892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_51042.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_241956.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_345681.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_35979.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_239579.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_89061.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_289286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_221499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_337142.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_285273.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_131171.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_234741.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_260025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_246987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_85843.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_345641.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_334484.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_310803.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_151168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_322176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_131718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_80560.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_121384.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_108655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_232835.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_8105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_277173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_359936.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_277765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_83410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_189997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_219849.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_174326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_121069.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_201110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_71345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_114508.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_226195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_26894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_178306.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_213461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_48113.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_93126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_87865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_96996.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_103173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_352747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_303896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_73179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_274905.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_157762.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_203032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_319562.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_375934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_359674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_204048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_377123.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_279917.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_165224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_328752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_238280.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_51807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_37263.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_236804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_316328.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_135096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_337091.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_122043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_167647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_292721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_340788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_198852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_243486.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_66670.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_202115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_159428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_247301.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_75729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_354052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_23645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_235299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_55944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_272472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_139576.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_195089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_326626.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_299872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_324926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_47417.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_140171.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_289588.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_116296.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_275997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_5309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_45645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_329888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_306047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_128778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_242927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_327480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_91772.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_280561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_73931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_292104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_78572.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_14051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_91297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_80392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_206343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_337515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_257106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_102832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_116555.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_240216.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_362683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_195150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_68009.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_259698.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_26554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_353377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_223418.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_364464.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_46029.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_197322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_360039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_140676.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_241950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_244792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_327753.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_146645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_334421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_216680.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_166461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_149940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_2981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_37601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_120262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_60132.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_191669.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_33889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_207795.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_285353.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_299916.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_311140.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_374679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_123551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_124737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_60584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_208244.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_17007.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_53059.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_23491.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_90107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_360385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_190972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_162378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_33603.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_236154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_371191.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_248634.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_189549.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_230560.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_110720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_214248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_190412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_297177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_238573.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_239297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_302018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_112964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_22231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_270678.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_43911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_163240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_379446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_105324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_197938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_251170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_137435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_184759.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_354069.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_52564.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_264363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_4587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_378782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_197376.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_285815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_105982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_79498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_300318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_361931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_51481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_280569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_79092.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_216058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_327256.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_344314.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_6396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_154864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_190359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_192119.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_235779.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_259174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_297632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_281467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_279290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_74899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_123661.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_157243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_25358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_146229.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_239220.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_249127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_171428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_240201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_147651.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_71509.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_318331.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_225823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_295515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_12341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_252109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_294524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_135852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_48072.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_98953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_300415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_135227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_129444.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_74841.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_73901.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_102593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_292462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_184199.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_196682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_180949.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_301396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_369278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_8345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_263724.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_116492.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_113778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_140778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_325830.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_57861.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_292725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_309500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_73377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_89617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_186604.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_208394.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_38357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_103404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_339215.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_92729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_107432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_22041.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_248927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_233313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_355253.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_145647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_69335.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_15713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_3929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_255800.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_336825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_371770.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_314115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_77879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_313147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_138179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_180116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_358533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_235570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_237589.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_35718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_9810.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_248464.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_186491.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_69498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_74001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_337270.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_220550.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_38376.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_357380.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_340066.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_221894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_155496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_48283.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_297542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_271693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_169858.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_182199.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_277404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_213486.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_10250.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_215463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_178464.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_45357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_210510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_70594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_233918.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_200652.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_259185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_318410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_260335.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_38071.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_85095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_285805.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_53767.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_198112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_202319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_47167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_8943.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_10493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_65038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_113739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_234272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_325575.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_32287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_21827.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_241731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_323674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_124112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_187185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_339214.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_366254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_251827.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_166978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_335028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_3276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_344938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_329069.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_260911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_365136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_344663.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_346021.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_331450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_21429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_291939.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_364873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_46095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_302852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_295409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_92176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_339699.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_241410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_212920.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_46145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_226175.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_354596.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_281029.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_119107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_164528.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_357541.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_305118.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_149777.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_113728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_189902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_329837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_228169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_85819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_219414.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_356110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_374515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_266896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_160930.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_121696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_289190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_298399.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_326826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_269952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_76681.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_264731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_160691.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_358976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_23137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_118165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_90165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_312538.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_312367.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_133763.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_220983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_25923.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_264067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_145816.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_329563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_250824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_257096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_32082.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_238889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_281299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_341864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_55395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_202482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_179597.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_26205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_9926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_166605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_72767.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_214557.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_93252.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_204776.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_224139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_312795.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_377887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_46302.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_322963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_144010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_102483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_150398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_128579.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_55919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_63950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_299517.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_349384.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_78514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_63905.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_156743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_366269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_274082.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_194255.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_267278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_123619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_116149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_277436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_355115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_211966.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_105224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_69020.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_355776.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_196162.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_136941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_123064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_82994.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_261911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_66821.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_354260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_264296.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_317161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_347428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_144700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_212841.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_14101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_312036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_277108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_162979.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_359470.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_87989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_294216.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_100300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_189747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_183189.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_87382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_194041.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_143504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_347893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_263252.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_51223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_270499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_316264.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_212963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_232844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_91307.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_291892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_164396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_13822.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_37427.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_146919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_55643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_330470.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_18533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_340360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_169291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_6498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_95004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_241720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_185497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_244144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_280119.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_79056.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_278226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_356022.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_200479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_188243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_33414.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_152367.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_87740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_369112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_323020.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_305063.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_222702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_46250.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_85872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_58146.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_279998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_47931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_339237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_99731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_74375.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_120555.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_144213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_216702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_140109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_122446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_183856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_210929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_165346.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_163249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_370892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_164655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_75214.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_108494.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_322805.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_94262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_373131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_21495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_140770.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_180662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_245838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_64416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_25847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_273563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_14289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_256881.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_139570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_234696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_42588.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_298023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_308163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_258961.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_98061.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_73947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_171717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_286130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_157879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_127551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_351980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_103460.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_210131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_140445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_235042.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_22642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_62377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_51015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_104213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_368813.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_66618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_48652.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_227973.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_135070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_308134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_117725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_207788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_37280.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_318937.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_375553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_72340.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_104546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_196778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_198023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_58928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_333535.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_168087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_121565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_262992.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_169225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_296358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_357425.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_39786.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_320513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_331010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_251330.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_191823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_160409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_320945.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_121997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_114671.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_330302.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_109543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_196723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_36265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_194188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_42377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_284945.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_177049.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_36733.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_260107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_304232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_187369.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_63428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_87613.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_351295.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_178253.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_360684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_26703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_276593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_372400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_233493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_25958.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_118092.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_180492.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_269806.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_112857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_193725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_5765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_192927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_220434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_67680.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_128120.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_89350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_156985.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_131310.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_54027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_243311.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_296612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_242874.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_214276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_241074.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_321840.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_372674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_86826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_166585.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_371326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_354837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_255421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_66087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_177944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_105387.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_309422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_317709.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_317717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_236447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_57032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_346181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_284422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_281414.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_158263.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_319968.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_64590.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_19480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_85817.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_22318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_204613.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_162788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_361823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_289763.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_83186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_345675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_23416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_322571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_14240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_48208.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_40735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_169584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_57363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_324521.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_150758.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_18390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_272638.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_122013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_310483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_319728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_27863.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_128678.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_88609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_195571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_110252.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_80718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_83561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_173339.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_64462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_36666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_177736.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_351304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_104333.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_250799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_10382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_157606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_361554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_166448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_316277.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_195134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_165527.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_67828.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_292572.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_70754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_141104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_61313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_160043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_302036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_17099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_17789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_239758.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_4028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_107913.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_95512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_262668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_319328.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_298919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_379388.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_28412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_301294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_208667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_351860.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_90707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_217672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_206749.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_301227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_35763.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_257799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_100542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_56000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_238473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_170519.qa.bqv
