/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14840.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7203.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18023.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10509.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4058.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3615.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10495.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16767.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7180.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19599.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9684.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1014.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4620.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1809.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11222.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8047.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15516.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8950.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11911.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15298.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1548.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11740.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7652.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1261.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13642.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15413.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6158.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18262.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18035.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15001.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10116.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11729.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4092.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4000.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6114.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4490.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18637.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11813.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/20139.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12825.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8028.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5300.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19586.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3856.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16084.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9533.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14303.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19243.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1089.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1267.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19309.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7505.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17667.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2387.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17893.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7295.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16142.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11160.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1621.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6429.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9758.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14543.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/795.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1982.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10196.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18133.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16693.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8274.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12712.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18536.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5031.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8678.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17439.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10776.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7259.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19473.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7714.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18996.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5772.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5256.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1037.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2767.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8530.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13365.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13501.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6927.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/774.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7979.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2874.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19455.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15626.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7880.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10239.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2922.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/996.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5119.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19519.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19615.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3652.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2735.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/133.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19136.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1329.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9515.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15791.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9272.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15431.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17329.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5295.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8975.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16786.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11958.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14357.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5305.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12435.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5745.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2388.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12752.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9479.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11918.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18013.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15650.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13787.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4252.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19904.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5438.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18087.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18363.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/914.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5366.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/472.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19101.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5473.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1409.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1675.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5859.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16990.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/284.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2048.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2747.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3062.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17042.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18858.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18701.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4433.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2732.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4793.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5262.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4832.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4276.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11513.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6249.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19850.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12726.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14678.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8376.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10176.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1984.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2237.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15087.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14325.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9298.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10071.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5193.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16451.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14252.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4300.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16045.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8292.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3421.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10790.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17375.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7553.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/929.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8311.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1695.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10954.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7717.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11916.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6050.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8736.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6285.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12739.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/787.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2449.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11696.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14471.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5748.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18301.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13874.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/90.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5196.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11451.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6971.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13961.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12848.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19652.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18053.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9739.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18926.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9728.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/600.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5092.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2698.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7807.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9550.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12524.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6486.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18069.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12295.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19740.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6199.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17153.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15351.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9574.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2094.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/779.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15022.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15857.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2178.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17364.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14755.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18205.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13245.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9001.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8360.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10798.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13950.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13703.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1740.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2746.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17285.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6878.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16664.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9921.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19951.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18934.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6755.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2419.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2254.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18907.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1674.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15547.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/421.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13055.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7828.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3641.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13094.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12805.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4798.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8977.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/700.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15854.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13759.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6939.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4910.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10736.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19100.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14031.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1456.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7577.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17787.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5439.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19677.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/20051.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15093.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15563.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14332.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13080.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19130.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12686.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8779.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4253.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18909.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3970.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15025.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12306.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15992.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13445.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5105.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13563.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5684.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5445.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12930.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10302.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9295.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17503.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17637.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9997.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16279.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18864.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17985.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3356.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19165.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15023.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6089.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13782.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/594.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7678.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7606.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10626.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7955.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6300.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/708.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17133.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/20003.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15854.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16268.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5045.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4976.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1389.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19756.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/441.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8377.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17314.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16207.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3093.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16969.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/671.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14890.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18230.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7651.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2770.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8869.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9883.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6016.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1709.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17190.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19128.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11920.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16264.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2257.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19382.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16869.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2943.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15824.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/578.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12305.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7642.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7541.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15977.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7609.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17852.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9173.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5434.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4047.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5197.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2592.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14994.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2208.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18450.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16691.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/844.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10811.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12927.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8483.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16853.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9830.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1772.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7714.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15792.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/553.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6629.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18324.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5523.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11055.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1950.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5623.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2790.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6688.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4894.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3054.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17044.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17131.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4176.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11206.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/181.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5849.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18268.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13758.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10101.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1197.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13664.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19540.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6424.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1862.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16494.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17670.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18469.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1481.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7812.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4109.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7678.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5802.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7936.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8757.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7361.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3180.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14879.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1452.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1448.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/371.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16149.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16093.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9854.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2440.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13460.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17981.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/304.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12451.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3202.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9154.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4154.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9868.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8100.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16698.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19504.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12570.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17249.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9971.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12577.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5975.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4122.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11140.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19543.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5738.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/20110.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8976.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6767.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2723.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6074.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1042.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19496.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7093.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4955.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2537.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5258.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9595.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15824.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17771.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2333.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16299.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14826.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17261.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17066.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15760.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15289.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14644.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13081.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18842.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4663.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2488.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12864.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16925.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18620.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12432.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15456.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5892.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1835.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12163.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3838.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18602.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1886.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16816.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15189.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4086.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11052.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9280.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/233.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/911.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5929.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/175.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14823.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14388.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17426.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11079.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14958.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/855.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15640.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8902.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/202.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19887.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11426.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14731.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16732.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8472.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1655.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6236.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15716.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9236.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1715.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11365.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4458.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17878.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8098.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16876.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5645.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13467.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4848.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13972.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9600.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10912.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16514.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10231.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11390.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13341.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9158.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17219.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4982.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3012.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3192.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19402.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10675.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3016.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1208.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11215.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4106.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13052.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13268.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6629.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17602.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14488.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15985.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/20070.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2838.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2720.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5314.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8779.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17021.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9643.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8097.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6219.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4318.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18421.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3308.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7445.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/909.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9057.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8694.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16754.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7262.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8233.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13820.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17043.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12384.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5666.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9070.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9657.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/20064.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4197.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18458.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8911.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6519.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11897.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9243.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9559.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17130.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12781.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3273.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16041.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18103.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14313.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14010.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5820.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7044.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11481.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10656.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3498.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16321.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9119.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19330.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9091.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17407.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13924.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6915.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8748.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18446.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8716.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8746.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13486.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14025.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/387.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12873.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1683.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17045.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16784.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4991.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11193.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3759.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5030.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2654.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6812.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1527.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15734.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7183.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13303.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7170.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11080.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16199.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8275.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2042.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7786.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6378.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/312.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16160.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9402.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7737.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10604.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14115.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16660.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19718.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8733.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7423.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7970.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17351.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1907.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/123.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3473.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4948.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1553.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4819.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/511.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/180.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9906.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17855.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13001.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3704.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13990.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7219.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15066.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19595.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3617.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11214.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15847.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10832.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11238.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5399.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4026.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10267.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/917.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2145.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14430.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14895.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2114.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8196.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7738.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15825.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6288.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7318.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9351.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12853.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16408.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8105.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15576.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13705.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14672.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18888.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7361.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2309.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8038.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10445.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17669.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19701.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5093.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4162.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6930.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13852.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15393.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10865.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6516.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15097.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11390.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4086.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6012.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14460.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14777.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19133.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13521.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9956.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19478.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16842.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11700.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11886.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/991.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6867.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16461.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6442.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6047.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7473.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15099.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/491.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7164.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12204.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19530.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12245.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18587.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5988.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3146.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/826.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4366.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14438.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1356.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12937.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2994.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15788.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1504.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11880.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/766.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12947.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12934.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16492.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5799.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10542.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8393.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13375.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8336.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2156.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19127.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5038.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9852.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18825.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19741.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11455.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2259.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12774.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11048.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15541.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19668.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5287.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13564.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4455.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17390.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6024.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4118.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16315.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13384.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6019.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15687.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4790.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17941.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/331.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/325.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16012.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12205.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5831.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17988.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1260.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7246.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4544.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3563.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4712.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9767.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5178.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12414.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2712.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13676.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5327.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13695.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8043.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14339.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9203.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2059.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5491.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13898.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17784.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4202.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13868.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/567.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17759.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18813.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17494.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13668.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4245.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/105.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13521.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19268.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7416.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13823.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19205.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17778.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16225.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/195.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16788.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6388.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4064.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8694.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5943.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15537.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12962.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14349.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8482.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8237.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16071.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5778.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15512.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16403.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/988.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9883.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16520.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/348.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4933.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5390.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1243.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4805.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13283.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16238.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2095.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15923.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11335.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18156.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6069.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18328.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3187.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3903.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13151.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16593.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3491.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15207.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18745.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16442.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1800.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14521.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14313.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18800.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5834.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14282.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18386.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12668.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15607.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5717.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15433.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/381.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4883.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17727.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17920.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11016.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/469.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7799.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2676.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6003.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9170.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12787.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4608.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/802.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18874.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7121.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16273.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14706.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18302.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19308.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7530.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6697.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14229.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3609.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7344.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16208.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12483.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19648.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18294.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3307.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18961.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17827.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4183.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16262.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3779.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17865.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14525.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1827.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4642.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6800.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1248.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1047.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7421.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14393.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6556.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19352.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17691.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18502.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3316.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12058.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7973.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12157.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2076.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4769.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19252.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13645.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5749.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13395.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/20175.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15171.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9897.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2482.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12566.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18107.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12398.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2026.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3317.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18337.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1716.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5816.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14235.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4504.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15590.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15450.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18063.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18653.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18696.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12952.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1942.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7644.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16085.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9690.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/159.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10701.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8667.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19042.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15983.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12273.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2957.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3361.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10103.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17490.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14082.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7285.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9667.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18476.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4376.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13771.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17939.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13365.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13157.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4481.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3398.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1153.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7903.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7372.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/322.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13795.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13319.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/15400.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19826.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7486.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11076.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14087.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17443.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3690.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/11816.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16825.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19401.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4093.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18399.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13031.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12733.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14945.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19823.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14474.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2004.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4021.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9766.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7891.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/17288.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18999.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16947.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/13335.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/19744.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/298.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/12224.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18659.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9045.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16033.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3510.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7302.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3003.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7291.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8226.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/2405.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18994.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/518.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/4177.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/261.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7127.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/9772.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8128.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/1764.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18575.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16548.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14326.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/8157.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/20121.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/16219.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/5573.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/3424.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/18851.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/10631.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/14958.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/6699.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/818.fna
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/285.faa
/cvmfs/data.galaxyproject.org/managed/plant_tribes/scaffolds/37Gv1.0/fasta/orthofinder/7125.fna
