/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig94389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig26569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig45160.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72160.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39242.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig126546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig95599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig201685.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig166309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig287644.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig278931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig167616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223337.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig148699.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig204720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig96853.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283384.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17411.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig255370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53399.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig245722.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27910.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig277539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig142928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig94227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig257137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig97935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig224763.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35979.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig137339.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115069.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig225151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig93387.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig217682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156755.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig212022.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig166068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238259.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig221330.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117365.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig136336.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig130445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig139819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig259225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57342.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156827.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284394.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig62348.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig265789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig45547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57716.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig192887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32182.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6555.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig90464.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig249556.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290802.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig222924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117750.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig45037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig224595.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig272633.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig177810.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra354.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig173563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238351.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38255.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284755.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig105920.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig114837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig166608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69923.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8990.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238863.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig126439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig121980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig105190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig216563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig92176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244140.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig91984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig160393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig253403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32610.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig82682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig214751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig139274.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58914.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig270896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig228786.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig102964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10021.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig218460.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig258482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199552.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig227768.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24843.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig105381.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra644.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135242.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig234064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147710.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig90678.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig80679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig269262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21113.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig197947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113491.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig281854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288697.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig84990.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig164529.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig127519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig127818.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig85536.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig152906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig205809.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260957.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig274734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig195151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig87913.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig116087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig262488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig216293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40354.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig182886.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig258572.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286219.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig105906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig209605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig200794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig242390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig83139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig152152.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig203415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6375.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig281770.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig275183.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig266320.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig245232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24354.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155219.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig268241.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig97141.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig148506.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig86766.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig134479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38810.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig79199.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig173817.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig276112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69430.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103758.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig180968.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4636.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20622.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig79275.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10937.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig207222.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig224670.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig154834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145961.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig172751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig207231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig46909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig154039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig74594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11029.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig2547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279939.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig110263.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15155.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6913.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig96328.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig169567.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig163973.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig107572.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig281993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig126870.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22271.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig33206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig97975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237121.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294691.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57833.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig137855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5054.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig106297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig176138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig276537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147229.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75588.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig142126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig214325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig83745.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig59909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210654.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig59847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42809.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig261050.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199796.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14562.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig182767.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191878.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig179529.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75204.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig136723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig56548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156948.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig140997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig160315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig248114.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra43.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155795.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125687.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig242473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig287042.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig128036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig164391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30346.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig85728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig116170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283175.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig110975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig161144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig59466.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig287978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig225885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16292.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47321.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115337.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103264.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig152486.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig261587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111588.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15114.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig278080.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig275257.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig179162.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30970.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig192937.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290526.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41592.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig183902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig48893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig96349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282741.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig240040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig141447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig192299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50768.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig227086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig56594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig77225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10762.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280849.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119706.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147651.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238182.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig214792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10648.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig56019.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig108621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig101961.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig91859.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig201052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig82113.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig66249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig175155.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig79269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig140468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig96534.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig261639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22002.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156241.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig176627.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250375.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig60954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig242148.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig136401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig224129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig92048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig193853.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig266436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig139040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19876.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288244.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig261298.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51016.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118552.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig180467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig195319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig221392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig100909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig46103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150424.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig182109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig64919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178245.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103680.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig181225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig90985.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig247194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig140959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292444.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig273608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20932.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25973.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig211134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig169606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig76469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig96887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282550.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117910.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig208271.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig252647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig258718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig45186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig80375.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14932.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig196179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5613.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig129227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285191.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239604.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig100908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50489.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267943.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119572.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27800.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig222647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159399.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig122217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9100.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig263423.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig219383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig67653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig84743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig256731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig65930.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig100878.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279753.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig106073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13625.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189384.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig124070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig60195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13848.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig98258.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35773.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113340.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig259038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14098.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig142187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig166006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig139715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig253729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig253199.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig259899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig182131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig129609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig295197.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig247771.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig87206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig240668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146581.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165641.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig177947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig78888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig196243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig79315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202366.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig74537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig268906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132312.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig3125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig128954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig158133.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220090.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig226810.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig230013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig90246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13475.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig229973.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150283.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig105627.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig195581.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig161386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig169672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig122865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig73140.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50486.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig116397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig201540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig169265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig95147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig217321.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15670.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162088.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18671.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58026.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig287786.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig101800.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig63721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103753.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig251094.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239394.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig128944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig49905.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig59496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238222.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189958.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104741.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19307.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159476.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig84330.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155910.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig121053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig62571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig77396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig154843.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig76505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig229319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig270262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145600.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig198660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5140.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig141569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293352.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig110320.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig268978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig129957.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig154395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig228863.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig233186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig68192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig63403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8366.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125748.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18771.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig107082.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig64065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig107009.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig204936.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig140007.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig148688.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187238.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig81749.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34780.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig140763.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288912.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig251390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig124194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig85525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig248108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig194284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20764.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig291065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288191.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig231293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294724.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13945.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290633.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig177929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig236556.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig197072.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig204477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig259371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig209714.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig46272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig201837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109828.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig76635.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191207.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig181037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig121269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig129715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284059.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig254496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23005.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig121018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig205145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239050.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113124.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig26331.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig175646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig253580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153712.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38066.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38862.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12581.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig173048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig200805.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig212269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61803.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig77224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig60584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig234986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig141455.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig177723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig215457.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig208735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig122002.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig91431.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47748.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig163561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig67064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61478.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34886.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186698.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig281951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293808.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig198983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig46359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244638.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig197743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig289892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig37233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig277877.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34239.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51029.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31859.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig154993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig198999.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47733.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36910.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig68672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210688.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig258131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig45717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235268.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig137793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig67500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig85278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17827.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165635.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig66998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig130501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig45467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186491.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig219796.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig137236.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99372.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig49858.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig275806.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185380.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig212791.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185418.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155460.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig142638.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25098.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig65642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32263.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig78803.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig183190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig52500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145979.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig171094.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig263217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig254427.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155056.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig142292.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig233590.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17576.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig256041.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig158924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig76179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10019.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig65995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig60459.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig37347.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig81365.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143828.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24658.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168974.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig268124.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig114310.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig160401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig275407.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41564.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156263.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig174903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig33872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig62543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109538.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig255325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig215662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig110950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig55551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig63784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig66116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig141662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig122107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig262642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig265702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig289555.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig106518.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104560.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig158008.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig157469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210939.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18394.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig73679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10535.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig193215.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig130904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig89531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186252.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig130092.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig209223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig217533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig134424.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig142898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig201393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig215064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig169000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22355.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145994.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig169087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig66447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig277370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189502.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig48659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283604.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288796.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109356.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178312.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig226422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149597.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17021.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig265231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185098.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36654.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig182952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig179818.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig68642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig171170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig218311.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig281805.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig124202.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig157044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig181340.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig37327.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig55112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig192519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig63995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig55678.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig249578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243347.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig152715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig37716.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig100822.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168777.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig37478.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig33511.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig234222.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig152648.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17484.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig166120.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig95284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig281134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig3328.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig82756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199877.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283746.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34384.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig171285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10426.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig127154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202767.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig203045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111518.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170882.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig154389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig209637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig124157.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig56142.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig140455.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig248677.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig60472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238868.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14724.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32722.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5506.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165620.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135074.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig52247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig77516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig81350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig263388.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig64417.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig91850.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113768.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig81659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36431.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig128361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22407.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23636.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig182388.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig84189.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25712.qa.bqv
