/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_61050.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_7168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_195492.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_16138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_118011.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_144310.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_38692.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_8140.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_95727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_84818.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_187934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_117755.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_63685.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_205550.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_195887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_20832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_115201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_38655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_193230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_51979.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_167612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_198769.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_138523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_142946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_93378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_179558.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_132848.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_67308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_139156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_108950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_2009.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_19993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_65271.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_34104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_162112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_61476.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_135844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_180816.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_202565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_36690.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_72304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_152300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_159282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_16525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_182602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_69470.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_1818.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_203757.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_208241.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_158218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_207493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_193946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_91898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_29517.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_160450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_144141.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_156610.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_171980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_91092.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_76218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_196809.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_78728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_4304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_196011.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_91386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_3639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_42268.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_129324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_99608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_214289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_5800.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_205559.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_28702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_93814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_209819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_44159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_149451.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_22310.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_96628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_13704.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_187840.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_44910.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_150833.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_1522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_206122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_12303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_51122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_9941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_194025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_13592.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_192127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_118664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_160387.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_8540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_134490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_7419.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_208743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_90113.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_85611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_79421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_103338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_39754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_162752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_109133.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_69882.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_45707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_93854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_141941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_137599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_147647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_75286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_204749.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_151169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_183729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_125683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_135376.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_56254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_179174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_117846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_162870.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_145713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_113231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_134778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_166029.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_134495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_177815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_12246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_160603.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_14997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_105309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_155968.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_24372.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_6578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_61789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_9605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_147588.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_48379.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_93424.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_152799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_190820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_124539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_162038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_134193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_144532.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_168043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_129790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_103464.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_124363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_26235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_127365.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_16859.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_33820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_58397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_92291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_92583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_194350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_61622.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_8748.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_93225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_96339.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_164629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_5892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_18063.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_4859.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_189537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_113121.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_83054.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_191962.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_38364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_151348.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_16737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_35430.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_186554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_29101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_185006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_94871.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_192154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_191429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_99764.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_3452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_199325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_106916.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_50570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_199272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_191909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_12416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_144259.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_45427.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_104172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_203860.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_106339.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_61094.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_122647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_145243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_110033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_76962.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_117816.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_203265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_110319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_34954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_63047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_210192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_54315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_121268.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_205158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_164228.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_201862.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_1114.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_474.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_93968.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_53008.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_31531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_189281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_59419.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_19667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_197341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_141557.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_74693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_76554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_25807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_68200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_127919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_19458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_122124.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_41465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_176105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_131318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_176070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_90898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_168980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_187266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_75285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_17599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_147135.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_20785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_200872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_141012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_152824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_194144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_195116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_141182.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_178735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_37439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_92619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_20440.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_166346.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_139501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_25782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_191334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_208587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_187831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_85550.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_195628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_46695.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_140017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_170450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_119916.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_138621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_114759.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_58629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_176538.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_184425.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_10920.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_181027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_8660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_111938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_104982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_10208.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_24868.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_153742.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_175210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_46727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_181146.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_159140.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_138666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_209797.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_164309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_166090.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_59747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_172052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_144023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_191369.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_163609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_67381.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_155376.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_3013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_3205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_197278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_4340.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_189799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_149093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_173319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_178450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_184479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_69991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_108179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_49766.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_189393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_100863.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_57336.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_27246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_96474.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_62118.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_44780.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_198616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_164414.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_87525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_42703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_177532.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_85422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_63831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_188392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_162518.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_126242.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_210197.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_106572.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_79700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_97973.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_179536.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_54059.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_18527.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_183730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_203234.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_129794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_162510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_119126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_75504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_113527.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_54879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_173511.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_71879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_40684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_79205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_54618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_129697.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_173663.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_179462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_10430.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_137395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_186456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_168515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_182697.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_39825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_87710.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_163170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_22607.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_105740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_196294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_182877.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_180167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_100104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_98475.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_209269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_121116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_188155.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_168015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_26015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_190245.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_51409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_109253.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_134916.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_182937.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_54870.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_124829.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_167118.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_14453.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_166364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_90472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_159177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_8647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_53206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_60686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_66010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_160749.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_109895.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_183166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_126692.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_183543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_150740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_86000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_171680.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_82672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_203732.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_202156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_135103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_34852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_108464.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_97766.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_98609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_88817.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_43707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_148208.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_38027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_15488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_114447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_38697.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_171719.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_157805.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_126682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_10441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_198043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_134367.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_13198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_188350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_163048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_116786.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_11948.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_86333.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_63490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_178315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_121941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_135463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_67449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_77265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_77603.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_116105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_23614.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_36134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_37844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_185886.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_155270.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_175119.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_90730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_155117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_201461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_57884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_13801.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_165609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_11946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_204527.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_152105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_185812.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_57124.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_7463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_21260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_4742.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_175940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_80363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_172933.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_157087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_90439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_4860.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_88341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_136791.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_146498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_99667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_88835.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_200536.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_109953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_156382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_133960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_151567.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_122587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_211992.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_124364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_28379.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_127099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_75396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_146865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_74730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_11015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_159702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_45582.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_212035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_13889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_16402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_159685.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_10627.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_209129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_23350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_178782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_30426.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_3498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_11635.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_23734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_166173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_149774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_139285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_3579.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_21546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_156332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_152360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_146975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_158707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_15840.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_77078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_167040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_166830.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_16496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_162285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_152453.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_207104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_19450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_21493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_193355.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_207013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_149503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_204121.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_57699.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_51644.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_73536.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_131888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_119345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_208104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_152651.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_150031.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_190369.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_22886.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_122080.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_131493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_147205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_147041.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_175319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_5272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_203417.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_181251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_118357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_176713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_107266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_171091.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_197045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_86474.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_16672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_56761.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_55586.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_24696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_34160.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_158328.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_28684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_189905.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_126317.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_81640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_205525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_142542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_166954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_173224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_28349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_14063.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_58939.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_190073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_195847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_185020.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_85181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_141189.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_150206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_163192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_68161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_107959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_38981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_165389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_79615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_194681.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_182598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_71102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_61462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_200504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_199472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_180515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_132811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_186023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_160588.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_164143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_153944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_60312.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_172032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_117727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_138948.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_92783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_118195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_96948.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_19872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_202389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_136144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_185165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_98296.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_27854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_117499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_117204.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_190646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_71587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_130584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_108771.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_162308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_108613.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_51297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_182632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_118616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_115298.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_75106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_129017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_181298.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_38826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_76622.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_148133.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_90904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_66807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_77229.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_174726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_158779.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_124290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_24287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_136529.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_97270.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_175043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_1415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_148112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_122782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_15811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_165904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_132617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_87101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_161034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_110309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_78784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_186225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_78247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_94617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_109154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_2666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_98805.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_5479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_46879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_90123.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_51512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_177743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_6323.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_15612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_110871.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_17464.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_173471.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_20632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_13601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_153250.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_53058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_76717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_99196.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_10265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_78001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_48330.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_119760.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_19803.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_25332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_175997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_134996.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_83793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_130175.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_186108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_44694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_6830.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_176612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_108852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_34045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_44454.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_180595.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_214710.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_119968.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_47748.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_185571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_80153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_110072.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_115405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_119553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_13799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_188423.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_3681.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_15201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_125102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_203784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_172174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_36256.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_186915.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_33349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_161400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_99881.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_66896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_188794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_136665.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_38243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_159976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_118370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_200702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_37269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_191789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_29933.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_104401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_8645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_117097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_109554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_149922.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_162202.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_113924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_19441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_2370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_11636.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_194071.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_168802.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_43357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_160407.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_99855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_122685.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_55723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_52897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_18904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_139561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_155406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_206807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_44990.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_66605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_38117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_202175.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_50122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_102345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_170133.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_17941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_106441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_183452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_71774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_157060.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_104232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_47439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_133446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_70753.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_104084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_128790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_197241.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_50281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_141031.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_200362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_17242.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_125217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_165846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_160074.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_62815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_190735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_130874.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_187048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_69516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_65370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_206253.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_205624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_106400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_28967.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_102769.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_32293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_146702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_67756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_117065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_118587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_126969.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_210355.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_10340.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_136501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_15086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_128831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_17639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_158876.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_42673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_85927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_161180.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_5258.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_102084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_111529.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_2613.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_4055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_177259.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_182911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_97932.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_163150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_69678.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_93958.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_103657.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_12169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_122448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_119791.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_181436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_99414.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_129950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_182751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_166001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_78315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_182294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_187472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_70713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_190500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_90713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_2883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_98743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_143316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_139084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_143105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_54431.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_74214.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_128862.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_8167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_162109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_45820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_99039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_207218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_93827.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_118477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_1794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_66346.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_7634.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_172534.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_46317.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_183511.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_205729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_142766.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_183779.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_183234.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_24703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_74210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_25257.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_4357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_144260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_163756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_109413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_30057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_175530.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_43278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_195199.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_122400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_79120.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_71136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_194701.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_114765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_172934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_117810.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_21367.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_14420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_32729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_142650.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_93631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_202130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_33524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_46557.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_133311.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_66797.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_165863.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_99712.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_18344.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_42428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_203035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_177479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_108991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_122680.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_60339.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_155179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_167462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_178669.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_77954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_179580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_53858.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_34653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_161375.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_143188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_90376.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_36612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_178371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_177415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_31878.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_149007.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_39927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_101498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_48482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_163625.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_153872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_126138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_162698.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_140854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_190851.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_6476.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_94640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_147183.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_158194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_16673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_25341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_9389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_176352.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_197696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_64333.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_136383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_118274.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_202001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_24978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_118191.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_91299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_204594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_195319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_134671.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_5790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_176581.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_141297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_49144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_188026.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_213696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_108989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_95331.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_92178.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_208555.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_167798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_179929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_50394.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_61211.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_132053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_129725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_68143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_102270.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_89373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_44467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_171258.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_206172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_137702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_110071.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_13652.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_10676.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_169076.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_16085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_159466.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_22329.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_135883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_20502.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_55038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_12775.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_194148.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_177422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_135128.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_97918.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_177073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_71767.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_130493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_128058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_192280.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_115099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_98782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_106146.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_6166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_82338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_6482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_159191.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_190193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_48328.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_141517.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_55304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_202021.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_185865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_180575.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_83740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_212415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_181694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_143355.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_166213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_26147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_204636.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_70269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_140176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_168579.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_134500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_71244.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_210998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_15017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_90178.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_78194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_65023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_169627.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_206092.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_146195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_208119.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_164489.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_133582.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_116802.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_189480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_76656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_181278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_168007.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_200293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_147806.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_148220.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_190906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_70554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_189177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_151868.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_204201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_30086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_117169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_39517.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_85694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_200614.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_205447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_113662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_150358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_42312.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_192093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_11169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_200402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/oryCun1/quality_scores/scaffold_484.qa.bqv
