/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig66741.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111780.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig87479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202614.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280770.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294335.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286572.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig173974.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig130452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig273617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig107684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig88911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32661.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig110830.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig175090.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig49020.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig242971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103351.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig76129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig55131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig83576.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig94754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig26720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig164307.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig276474.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig193411.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig295234.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig26477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig166717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig139779.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig209133.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig226321.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125066.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11072.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig249147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig160964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190582.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig174087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162376.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig106972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig233917.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239558.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig167360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146676.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig287326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig251242.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig233656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig261934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig56994.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig130642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig83356.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235822.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig116639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig101166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig95738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig172564.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282466.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig251441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig79522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145712.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig198232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119636.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig48887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig77181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig225149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig234004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig79249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig177670.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig193370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69915.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig130087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig33406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig37221.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294688.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig257854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig197262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32806.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig77262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18492.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184851.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig114738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210835.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig116833.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig204329.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig219776.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig142137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig183658.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig242475.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig201002.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig123615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185716.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig124575.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig204311.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig219652.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190098.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig219997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig209300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig205212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig120499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig218110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig63295.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7753.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22744.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38691.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig198089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig208571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig62831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284843.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig252434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig208309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig136229.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig59123.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig289171.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243228.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig108142.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig174782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15347.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig275240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig96545.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig211794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig107623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig106160.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig108725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig137359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig76759.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig278605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig48033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17748.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig83218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig201524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig176321.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44191.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig158439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig182420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19970.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159478.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig225895.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig183195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig204990.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29142.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig173145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig266754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig265465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187354.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117744.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186258.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig172399.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig175584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig198446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig148153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig89630.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17305.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig262046.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig3605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig206851.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7239.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22557.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159708.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig274007.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig122521.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig169609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57029.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig48419.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22311.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig217333.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig215952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig90017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig205798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig181920.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig100636.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22776.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig48879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig219278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17066.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5836.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig218854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig37791.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35288.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35536.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199979.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig81601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135080.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288457.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig59502.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig228983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig200581.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig228097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig176247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig55574.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig88753.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig276532.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28916.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig206272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig120927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285770.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig254520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213589.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220812.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig200452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig196060.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig110053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig222485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig154256.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig152534.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189966.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191433.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283264.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig204479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig126308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig274701.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig123501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig233419.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286255.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig171103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig56565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig197987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig128653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig64957.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223228.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69779.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223518.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig100092.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig262706.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig272795.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185229.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig137802.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31829.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155252.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16801.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig167766.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig55416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40507.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig173438.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig122461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig73863.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig195600.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16945.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig101672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15424.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168484.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig247051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5492.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig215536.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig287432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24175.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig89993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282388.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig196748.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig277233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149665.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig276713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111695.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig192430.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig204369.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig281455.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig49144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig236904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig252754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig55527.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29663.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig124935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig73077.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25709.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig234017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig236505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31545.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189155.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260081.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241913.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292772.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig67093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213365.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig107194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145577.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57719.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig248262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig219017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig229456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186973.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig225720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75733.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig55109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig281826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36060.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99336.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig45377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig85398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig52874.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig141187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig291783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig62228.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150229.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig85466.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig247712.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig83390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168242.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47255.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283763.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig120766.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig122790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig172991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig200346.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig106764.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig224209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155882.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig87465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig89337.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig98995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig254007.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig233850.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig123103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig142730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10969.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113638.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig74851.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191592.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147780.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig79354.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig108487.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig196977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig141646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig177045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210059.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32699.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig229479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig231009.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig180812.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig95004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25189.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig287027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7487.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig234164.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig225908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig269420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156528.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig84088.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig212983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig102222.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig90879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19648.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58353.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig255309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185351.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig45288.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71366.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig251416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig97613.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig245824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig236653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig177703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132905.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig3390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig249942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig230017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig67327.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig26522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig157863.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig134502.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig287139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig163756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig214624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig252223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig236891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig277701.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig76025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig211594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53517.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig240149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43671.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig68434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig76686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27985.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig80000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149534.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199259.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25932.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8433.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146407.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig101861.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig46477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig180919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig232734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig83376.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig123230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239189.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239280.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig181554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig200010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig257833.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24529.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig287143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125298.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31331.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9845.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig217809.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10487.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig129897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41545.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig172096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12261.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70810.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig37161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig179663.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig192134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig116919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43342.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig251991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig255107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig230496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30914.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig228682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig128901.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig274575.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191585.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119878.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig127723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8648.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig179730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig67267.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig277468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig208362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig203416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig261389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig166469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144777.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig212963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig157048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig141206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig129965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig245763.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290746.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig136902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig214962.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig172073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig68048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig160557.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig217129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159766.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig173449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig232745.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig161058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61492.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144698.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47809.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig64040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig161940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig3524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig161022.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294288.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig169528.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58440.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig91721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig164707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig92818.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig209332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig76137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig253266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig108004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig123253.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23962.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig89297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165444.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig251177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119426.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162454.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig60428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig26932.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43710.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig88857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15641.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig262867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig116873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig172614.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig197474.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189634.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32538.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246369.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283780.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig141938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75603.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238689.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig90284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig110928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig216378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig78227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig171477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50118.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig88670.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig105805.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig197042.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig221065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig114956.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig242430.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12202.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig274995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig126564.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig225451.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig122341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53772.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig261396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig245189.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig257439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31022.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig3609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30301.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig107680.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig251238.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16459.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig254366.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig164099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig176718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243596.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig78544.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12075.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244590.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71268.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig26261.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147407.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig227079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig227143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290962.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103492.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17063.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig180507.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146755.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig231507.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra691.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47356.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig98734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig221276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig128710.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig203126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70658.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig136520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig79696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283736.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig129913.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig3624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig163576.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig226070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig226574.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig94051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig80871.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig217295.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig62853.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig277613.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294671.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig59206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig63454.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31337.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig139368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig249476.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig174327.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig3912.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig172006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig225282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292709.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig229064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53171.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig157615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig91742.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig166275.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig219164.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31985.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig152688.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig64198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210414.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189119.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig60659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29755.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig242574.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118915.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig181856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131296.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50913.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162241.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28607.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig251074.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig224040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig200747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170352.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig193788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61340.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig116490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig206839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig126419.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155094.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig90216.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294830.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69648.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig48773.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178843.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig172860.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig120729.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig245182.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig94131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146966.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig77600.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig92317.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig278177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig256940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11572.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235339.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig48786.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig204929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24564.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig193867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153923.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig3082.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig214891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig137454.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig123446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig59412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig259076.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig134262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143453.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28544.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig158093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig126592.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig281566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig52173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig158214.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig232106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165491.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260423.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig140945.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig252532.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig208774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig141018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35871.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig151507.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig92507.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig173538.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118776.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig224755.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig79109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig277629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54024.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71764.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig140770.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig3045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144994.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig289190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig121820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig160978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig211879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig90917.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250092.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig236212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig259998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig276510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig262132.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41517.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig205095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28711.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig116468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra575.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig249879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290663.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22930.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260577.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig236923.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig166330.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig172737.qa.bqv
