/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig32987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig29070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig44730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig34379.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig103483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig92172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig57976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig92697.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig26897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig51888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig18980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig12165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig31199.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig29364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig12184.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig97181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig49366.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig4620.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig76812.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig43435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig40556.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig103869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig60566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig70102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig61198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig24449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig33202.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig60515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig79075.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig98927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig60504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig25455.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig11000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig36838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig15877.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig95886.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig23723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig7741.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig44253.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig104040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig69839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig58046.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig77956.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig33341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig32734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig40322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig48611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig94311.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig22344.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig77015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig95018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig45983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig25673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig20396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig96153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig42846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig21134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig97716.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig65813.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig100891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig62788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig33972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig10928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig74094.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig84459.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig78129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig17139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig41807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig23382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig69072.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig6727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig62070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig80263.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig12041.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig22356.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig65962.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig104251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig15145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig74165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig84710.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig14027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig35103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig19083.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig5651.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig97596.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig25126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig54488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig30555.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig6040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig13022.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig101814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig82058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig3988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig19837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig93342.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig71830.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig7343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig47674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig74518.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig17629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig44669.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig105150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig83379.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig37368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig104641.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig78403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig93772.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig25891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig91076.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig7533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig85418.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig55037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig95180.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig59864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig45675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig79784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig44537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig97753.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig36597.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig51512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig36542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig41464.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig51288.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig63554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig105550.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig47835.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig97814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig37324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig83619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig96894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig13988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig35284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig51099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig105950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig73135.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig101371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig87621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig24992.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig47487.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig17378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig47804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig8333.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig81413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig81185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig3680.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig103812.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig30820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig86064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig9124.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig91304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig14124.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig53858.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig27567.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig8679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig43902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig25355.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig31461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig51412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig80825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig11989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig28410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig57083.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig38825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig32315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig89103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig38609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig102154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig105114.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig26829.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig81308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig83656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig27540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig89415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig13390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig14547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig102127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig5234.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig57620.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig74811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig107702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig46421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig60690.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig61152.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig78187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig68799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig43515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig96991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig36401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig94716.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig88265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig57751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig26199.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig12565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig41353.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig46011.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig33701.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig66810.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig88207.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig44026.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig31905.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig73249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig70977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99603.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig11965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig59836.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig18010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig65.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig83532.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig49747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig103306.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig95658.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig92906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig22637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig74032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig55958.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig105111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig63167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig17196.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig36715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig107232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig18027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig2883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig9541.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig16131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig90679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig43752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig52042.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig61156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig95998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig43746.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig50822.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig76616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig98320.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig61210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig47854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig47939.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig56636.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig20027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig6612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig88512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig86773.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig90337.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig3927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig80884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig36994.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig95206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig47220.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig90376.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig2934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig44677.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig1048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig102860.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig56227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig45739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig85686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig104495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig34781.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig39485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig100824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig44675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig27268.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig73232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig40697.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig53623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig101524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig62799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig1842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig12287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig49123.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig6240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig46145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig76665.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig2053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig14636.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99387.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig61157.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig64205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig10673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig34179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig31790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig38435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig84286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig71954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig67236.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99545.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig38446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig21932.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig89374.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig44421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig90771.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig82721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig91558.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig58214.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig101940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig58805.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig94935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig61171.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig84865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig76593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig30504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig105176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig84931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig82934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig101669.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig33098.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig46961.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig46002.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig17715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig62667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig55363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99990.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig14429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig36830.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig44668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig4423.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig77601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig75595.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig38389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig106372.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig80052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig96280.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig94833.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig60807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig6602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig92889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig21711.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig87201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig35823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig64429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig16357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig52467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig28787.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig56963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig24477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig17332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig67591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig65849.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig24591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig74870.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig15518.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig71196.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig60825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig39332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig65812.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig27687.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig43458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig76839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig17339.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig26276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig72371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig84855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig95869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig66510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig31976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig108163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig33061.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig77347.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig17966.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig71504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig464.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig101928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig14038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig34349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig85274.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig1057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig1084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig21475.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig103639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig44159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig589.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig58694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig80996.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig21486.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig64930.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig47197.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig31290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig42893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig59525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig33840.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig71740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig2206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig75033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig22750.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig28619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig78217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig77170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig3828.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig72103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig59762.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig43764.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig64195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig41861.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig50212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig45405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig20325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig103859.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig20125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig11142.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig85059.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig13560.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig79957.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig75137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig79490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig94019.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig70985.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig101420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig30645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig101212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig83086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig37079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig52623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig3614.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig30758.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig95725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig31023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig8483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig39321.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig63051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig38020.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig92257.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig88551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig78906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig93918.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig98678.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig80725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig83062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig103280.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig90997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig47177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig88123.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig107404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig189.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig11444.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig51587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig3170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig108169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig8057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig57474.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig25206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig57493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig60119.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig54386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig65408.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig25681.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig57444.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig12670.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig14087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig87138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig53053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig59025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig76544.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig68759.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig60977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig66684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig8558.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig19879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig2434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig79878.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig27439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig96323.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig45792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig26632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig68815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig22976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig57814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig26769.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig31717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig55869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig81758.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig92589.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig93634.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig74758.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig59628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig64166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig24224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig86736.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig9287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig91014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig90928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig88889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig24213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig8951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig63907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig79449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig41599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig44815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig88455.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig32622.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig2759.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig42605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig18903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig83954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig53621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig52537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig88507.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig66130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig14530.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig55912.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig27861.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig106391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig88233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig63386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig64352.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig51460.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig53496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig83442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig49182.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig91075.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99295.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig1616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig27994.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig19981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig1811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig25699.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig35162.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig58673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig34929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig86254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig77704.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig79940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig37343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig15325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig93341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig22798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig24633.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig67115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig70993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig29987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig20804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig30612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig53216.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig59744.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig80372.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig67712.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig51823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig108074.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig51300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig45008.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig12216.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig7178.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig73099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig96454.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig1178.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig88733.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig22844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig79825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig98065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig48318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig50108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig17256.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig100400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig19217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig84519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig85062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig26432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig75937.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig66269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig74847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig21429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig61703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig93725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig81976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig44332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig52131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig3027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig59335.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig79798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig5870.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig46039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig20048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig36109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig59272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig102771.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig82484.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig37139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig84949.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig15817.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig83737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig100278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig79187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig66902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig69728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig87548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig19240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig25878.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig20846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig69428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig21976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig24770.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig11798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig19590.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig39034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig86767.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig104350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig24954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig100623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig47417.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig52853.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig100313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig72318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig17406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig106856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig60181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig53662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig755.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig39916.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig10695.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig24879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig34496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig17359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig56394.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig41226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig25796.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig30143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig51702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig95640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig18269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig15573.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig105490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig56260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig57542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig44383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig12877.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig11370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig108168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig58735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig87226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig35210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig81822.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig105638.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig50543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig60605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig3084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig3631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig45262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig27180.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig36441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig5655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig59534.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig64649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig10952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig80027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig88479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig24495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig93113.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig68730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig88545.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig33927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig106936.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig61151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig37617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig17419.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig85696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig68861.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig83087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig65293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig44791.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig92849.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig7934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig50332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig55060.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig57427.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig3016.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig91232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig105462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig39895.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig55253.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig69723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig8522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig71388.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig101345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig31237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig74375.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig100804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig16528.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig71674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig10221.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig68186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig51249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig88504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig41783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig45315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig81183.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig30885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig11575.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig53070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig80139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig6461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig88898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig79411.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig73899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig30505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig21847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig46553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig11220.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig61003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig80955.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig32063.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig36245.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig44559.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig102197.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig68440.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig31186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig12471.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig77470.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig90746.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig60085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig26872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig91731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig80919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig35616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig86407.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig86952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig27649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig28243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig77967.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig43799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig84766.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig30481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig58793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig9945.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig9076.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig64752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig4924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig13177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig42862.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig15666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig62870.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig9793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig2064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig3304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig50696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig53269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig22576.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99366.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig6849.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig61150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig23487.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig17481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig86516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig15131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig58540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig40833.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig15773.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig28620.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig17297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig56721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig87149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig56629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig42698.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig10551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig41687.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig57863.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig83048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig41188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig77127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig86392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig35845.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig98098.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig58260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig1473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig33515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig57541.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig10577.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig101232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig36797.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig28611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig18920.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig70413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig41515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig67238.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig97389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig3767.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig97344.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig8084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig70152.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig47150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig62935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig106481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig64631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig83245.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig7647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig73715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig98399.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig69747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig12382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig45794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig92351.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig22421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig50455.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig2094.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig54032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig68531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig4511.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig84474.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig63681.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig16475.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig61497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig85169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig14079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig26135.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig40623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig69352.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig69273.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig2472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig74223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig52152.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig8372.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig50931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig68045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig51018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig40665.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig93405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig41371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig59712.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig40853.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig82178.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig66312.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig75432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig62769.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig2725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig19664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig42663.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig79070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig95636.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig61463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig8791.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig75068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig69458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig58435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig5676.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig37705.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig94188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig86289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig46309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig80398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig43898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig98911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig56005.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig63040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig36911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig54233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig93537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig30679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig81498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig52948.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig7383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig28918.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig53989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig28799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig82065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig34433.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig51975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig103885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig42768.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig56015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig52490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig75385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig94944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig72159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig39675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig57483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig2016.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig73345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig45475.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig43970.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig42567.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig38797.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig56605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig13016.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig62465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig33971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig5542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig77006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig105511.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig15138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig27869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig82803.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig94432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig105157.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig72964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig19028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig60915.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig14213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig8963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig19566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig66360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig31676.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig45493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig65571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig31210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig65236.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig97426.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig1744.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig64890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig42352.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig80028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig18314.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig13978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig105656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig14095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig101431.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig49264.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig92816.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig46855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig23034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig5312.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig48393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig27670.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig93610.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig69891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig90243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig83184.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig104054.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig65707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig37222.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig3655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig90570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig82350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig61743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig7299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig69171.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig92025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig14005.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig65341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig7855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig22494.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig37034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig30214.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig55173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig88580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig103247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig36136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig71241.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig11016.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig69971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig27904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig95257.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig107056.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig15479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig76241.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig13319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig92146.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig18059.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig96078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig37207.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig75850.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig90723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig92469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig90705.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig18783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig46965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig38841.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig4773.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig63012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig70692.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig51263.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig97981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig59599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig97674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig80570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig36933.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig66444.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig58305.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig12463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig23889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig82787.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig55541.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig77457.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig86712.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig87777.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig52503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig12138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig99099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig70432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig1534.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig37032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig37421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig86580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig54161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig60608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig87278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/petMar1/quality_scores/Contig31394.qa.bqv
