/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_240041.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_240883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_149790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_23685.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_123446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_286997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_346784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_153181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_203338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_39230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_253293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_275945.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_89834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_63996.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_58697.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_141889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_134249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_71799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_205209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_292686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_240902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_69067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_242461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_202180.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_138363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_230872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_223532.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_257731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_214104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_11691.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_300959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_341883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_123974.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_250268.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_180707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_17795.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_133889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_338140.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_260357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_340883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_115882.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_34939.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_18866.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_303598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_324856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_324772.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_194454.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_221132.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_377382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_279658.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_129865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_6895.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_43987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_53029.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_117907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_336683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_321845.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_187110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_73566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_95232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_364055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_76030.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_212737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_68765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_111903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_85997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_6924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_110238.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_308585.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_144624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_368506.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_109585.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_59043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_265227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_306412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_39016.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_4319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_181910.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_217522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_218960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_103685.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_33823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_349688.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_42641.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_66640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_295645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_184366.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_205232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_214194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_3358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_297828.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_214696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_336319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_260316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_279242.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_270646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_50203.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_222651.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_300821.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_125548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_248841.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_276582.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_134435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_138585.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_176306.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_182862.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_334664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_266757.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_221277.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_162302.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_195996.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_361082.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_45572.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_113981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_165620.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_356083.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_235108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_178382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_135825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_121068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_41567.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_101765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_26084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_78546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_260826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_128889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_252975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_314164.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_23117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_180851.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_352887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_352855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_53441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_56944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_236259.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_283794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_107769.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_122381.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_125566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_359873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_147639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_16608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_260270.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_375610.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_32071.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_208181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_318943.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_105754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_100358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_350828.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_29031.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_125676.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_320548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_189391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_38946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_36482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_256792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_247831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_65867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_106063.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_287373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_165938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_358338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_290608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_233013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_23235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_98441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_90385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_258113.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_280678.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_289390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_376861.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_42515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_247930.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_91549.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_353420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_178713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_330353.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_20531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_327107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_185141.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_7553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_135007.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_267215.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_278643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_122269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_105856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_343773.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_162274.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_301376.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_63235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_75981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_77077.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_161573.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_118920.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_247445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_24593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_257170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_364738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_17588.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_125932.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_46503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_239003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_171090.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_195573.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_232525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_253024.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_19504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_339254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_28675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_321186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_23639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_246909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_41218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_70621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_374075.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_200657.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_365653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_24683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_92609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_288326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_349350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_83694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_145450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_281717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_145218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_320497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_220510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_100632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_154386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_249209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_361185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_354350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_290862.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_76264.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_113031.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_120870.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_12839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_184405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_297270.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_196388.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_194369.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_42524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_213619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_195241.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_62898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_48429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_74302.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_365457.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_255159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_354936.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_185496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_31553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_78330.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_178275.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_23127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_78349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_5388.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_355108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_262647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_80627.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_183244.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_219652.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_157380.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_158413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_22769.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_86041.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_173637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_6715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_100495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_185300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_143304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_61548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_152303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_297137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_24458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_355306.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_33613.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_201103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_309011.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_34100.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_143601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_13433.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_58382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_79235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_150657.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_162476.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_82120.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_310034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_276370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_241963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_104685.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_221008.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_81517.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_142654.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_261296.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_363859.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_335976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_304163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_171969.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_162839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_75907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_316257.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_120134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_24143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_83876.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_379661.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_378311.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_188958.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_757.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_311720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_125143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_39150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_237037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_255184.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_9332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_312117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_83132.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_28733.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_311942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_242607.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_328461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_93722.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_342953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_105358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_87642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_266578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_293834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_307450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_130677.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_301883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_55981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_64210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_359304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_267822.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_23741.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_321521.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_292632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_299902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_246377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_40415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_162876.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_240558.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_182012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_1659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_249782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_65863.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_48984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_211192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_4131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_280559.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_163773.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_153137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_202349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_66402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_58990.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_318014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_340570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_9483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_138310.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_212906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_74446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_286342.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_15395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_136790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_63579.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_130876.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_82378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_46256.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_272518.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_43538.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_237165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_347743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_256546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_357074.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_278445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_278999.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_9279.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_54820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_39999.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_296172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_283724.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_110554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_134145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_130282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_308459.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_235022.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_179890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_181457.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_170426.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_239546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_234045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_368966.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_21646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_9877.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_238919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_363196.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_295545.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_293691.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_57779.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_102319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_2522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_190590.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_97752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_313418.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_73982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_8790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_196161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_250651.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_97385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_168200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_205472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_215350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_327597.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_228007.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_96100.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_125983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_25403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_299415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_282107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_181784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_294351.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_276906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_223010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_140576.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_236820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_265208.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_184522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_120289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_273167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_364399.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_137656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_19765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_241142.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_263846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_103017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_265249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_324707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_95996.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_65263.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_6776.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_358069.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_28931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_337488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_321156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_320590.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_95047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_125439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_33642.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_229395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_240361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_218467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_245672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_46568.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_117750.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_256748.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_259454.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_246282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_191543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_139061.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_335353.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_159407.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_158656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_195458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_145425.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_62160.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_135148.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_122079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_273842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_55181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_254456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_116624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_65221.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_67637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_180060.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_374766.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_64422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_141620.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_104315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_158581.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_315427.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_266331.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_67058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_81108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_45169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_156165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_151117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_98842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_113049.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_105962.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_292616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_178249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_291605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_252839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_345138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_338214.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_24493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_99212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_118995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_189660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_62844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_122399.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_214539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_165294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_146155.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_280953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_331470.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_153622.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_91121.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_138922.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_206466.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_283480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_276101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_15682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_231940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_19969.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_310988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_72933.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_100637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_3588.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_148158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_315553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_74066.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_367248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_335105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_105067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_38276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_350585.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_378279.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_232364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_120716.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_115495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_86827.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_55505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_109861.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_288142.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_335287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_35313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_172657.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_225880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_186602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_309040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_354860.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_288645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_186573.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_80018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_117102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_336356.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_315754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_302146.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_267785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_342935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_302619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_325532.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_179924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_307134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_169971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_234281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_7861.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_128007.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_215580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_206111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_160953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_166352.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_140439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_257951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_353891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_71388.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_350501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_64575.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_343609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_85216.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_161526.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_250784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_33054.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_369115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_257700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_69416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_342556.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_134322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_99278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_25946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_178812.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_303321.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_65558.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_28941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_104758.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_225193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_366456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_97115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_233914.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_354562.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_222101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_182950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_39180.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_367036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_8033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_340088.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_185818.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_65407.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_56226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_336508.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_359335.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_79269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_218087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_39089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_144855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_129916.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_350524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_17148.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_309959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_26308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_302386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_344260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_340820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_258161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_44035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_342307.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_227691.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_140101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_163785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_68666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_324875.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_9840.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_156843.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_183019.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_109711.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_308658.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_63605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_288930.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_146171.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_93233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_306488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_116725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_321103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_338994.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_59622.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_70626.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_144677.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_355707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_304338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_322698.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_82743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_221582.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_236173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_248727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_296510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_289513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_347828.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_217956.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_319193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_42569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_281401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_209221.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_3334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_265602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_149695.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_70232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_44249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_161449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_224213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_282712.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_182377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_188576.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_260905.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_26200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_346994.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_99348.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_249327.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_322507.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_339533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_160157.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_321874.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_90417.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_258168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_378586.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_62541.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_9259.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_126578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_351518.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_126377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_190663.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_82097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_247855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_131886.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_204343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_62113.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_370579.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_214093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_263977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_264326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_233311.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_55032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_184309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_64253.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_354116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_80125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_164338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_121184.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_252773.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_274286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_331519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_136570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_5658.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_311145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_106229.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_330635.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_370909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_317538.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_253436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_1703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_342330.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_179159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_141385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_66288.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_174600.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_98599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_13925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_350848.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_328043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_185291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_34314.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_322077.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_44421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_261783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_258006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_374285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_264748.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_90591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_363626.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_322038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_309771.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_36669.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_279612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_221593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_357929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_62862.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_364774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_117835.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_198082.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_121797.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_312649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_173871.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_40652.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_4515.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_102338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_188061.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_44811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_1398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_240136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_330462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_190467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_161114.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_69270.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_325285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_146209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_292692.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_121650.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_105269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_368134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_82046.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_151761.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_90378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_251731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_23669.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_261473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_213460.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_291862.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_272808.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_20879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_112867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_68900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_331910.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_136902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_326652.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_102274.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_171076.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_273606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_359267.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_262958.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_292353.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_42158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_152352.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_93567.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_170991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_377497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_118872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_1471.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_275249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_349946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_189389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_102745.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_214082.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_351781.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_71321.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_5158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_226248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_178513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_10611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_43284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_3499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_150633.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_316044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_121952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_60640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_157340.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_201914.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_362368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_15369.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_92197.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_371047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_86736.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_239143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_41152.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_335881.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_198063.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_132546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_267259.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_102574.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_172846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_127379.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_1490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_249591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_318310.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_120972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_146560.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_35132.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_146357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_5656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_271326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_314915.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_311184.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_33966.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_272100.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_17103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_182459.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_30855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_118480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_97829.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_281292.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_274531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_129473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_101274.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_178120.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_65414.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_314689.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_57890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_304332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_74177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_203209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_366466.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_18800.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_269718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_277433.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_50330.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_191014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_157246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_208546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_242076.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_318635.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_61144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_182626.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_112732.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_208127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_32680.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_113172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_99183.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_6214.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_125656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_319349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_181245.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_315868.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_251897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_65502.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_184086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_158312.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_196724.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_337684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_95194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_1452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_252204.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_54686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_158924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_139294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_292025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_259039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_295259.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_124897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_309193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_3790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_132239.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_82891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_114020.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_49074.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_835.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_285163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_251383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_311728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_195429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_267838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_346208.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_161538.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_89385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_357084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_123628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_139198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_61299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_228645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_25746.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_132168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_219457.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_374954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_273289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_252598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_302557.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_332344.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_119074.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_78226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_140927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_153990.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_292896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_302952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_274479.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_234522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_29046.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_168112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_178608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_45481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_369450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_251079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_196152.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_106200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_61661.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_250399.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_283615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_160517.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_131302.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_252752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_129899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_378088.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_330281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_281561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_183583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_72843.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_95410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_140170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_310381.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_109309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_19604.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_274005.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_81149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_120002.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_88619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_92024.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_5395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_190816.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_323070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_137015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_233155.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_355322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_78297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_171997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_234712.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_348122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_332033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_229635.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_175844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_47763.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_284227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_217353.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_76275.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_110231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_44257.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_7301.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_82272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_179311.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_348668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_223292.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_142623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_133260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_297900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_160540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_348415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_246723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_173408.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_271450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_14379.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_250539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_312496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_156034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_304490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_375877.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_134153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_285246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_102215.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_189403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_161006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_353177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/eriEur1/quality_scores/scaffold_12125.qa.bqv
