/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155549.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_171665.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_145670.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211994.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138626.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_76106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_128486.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_217235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_160764.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136870.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_69630.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109853.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_194756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_111202.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_180829.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_61691.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20005.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17576.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_113897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_169770.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134695.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_125319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_69982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_82608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13301.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101732.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136478.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17146.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155019.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_165110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_60337.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_47949.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207958.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_160105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_4842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_28150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212317.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94968.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_84497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_92028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_41563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_7949.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_61374.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187957.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_100212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187691.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_115683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29453.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79802.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_168169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_83503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_14910.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_28831.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_72009.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146550.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_76711.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196758.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159701.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_203734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_61612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_41880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_141096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189031.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_153718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210586.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_147694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_31483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_152032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_131180.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142026.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_84570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55800.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97758.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216967.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_215570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_147327.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_205754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175795.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_201999.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_76839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_47024.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_69627.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_23079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149781.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_185088.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_147537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75113.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_150422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117080.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_130006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_160004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98716.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_217451.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198859.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_172456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_52391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_183964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_14931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93277.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117219.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_41893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_37799.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_23964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_100370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_184049.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_73303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_113645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_84522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_18086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_173874.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_125651.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_50341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_176947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135113.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_40993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_171732.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_33947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_150909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157681.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49604.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143347.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175816.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_76552.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_73163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3305.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3335.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75207.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68506.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13071.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_130059.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8921.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_127384.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_165722.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97724.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_18143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_46264.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_122957.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_60868.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20795.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178414.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_200904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_64707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_37824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96802.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_167183.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142268.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_131082.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1474.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_200940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213845.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_15522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_40813.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114250.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_5663.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_188456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_19188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75748.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_51982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_15350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_169168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_164990.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216556.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_151888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_84901.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_208791.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198596.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80380.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166895.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157687.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_66668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_130300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_14566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155228.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_131313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157431.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129833.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_52467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_124425.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_152621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_156879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77999.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_127785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107767.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_61055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_60987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175081.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114730.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175806.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13895.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_190727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186558.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_217540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_153605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74710.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_89877.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_19912.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8220.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_141247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101848.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_7381.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105296.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55544.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_112149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97777.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32663.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48211.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95916.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211019.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58638.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88438.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_82554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96076.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6574.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_50047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58220.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_203908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_200976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85638.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96346.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108128.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_128064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6211.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129712.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_160021.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_73249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182801.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_203226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_172780.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_131836.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118162.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_150495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216779.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_9844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_140879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_103199.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_4874.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_64139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_130532.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_201845.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196690.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_82061.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137717.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45809.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135596.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187009.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_37604.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6273.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_90461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189142.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210697.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161614.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_84875.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154007.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_69658.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96691.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24083.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_15595.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_150784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_19144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106827.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_130797.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158716.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_69402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_72899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29268.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202408.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133214.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_185517.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_81932.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_100736.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_214830.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_215976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_163899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_33045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193994.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39321.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_66414.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143558.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_89983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_168106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_56545.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96091.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_113954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88518.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_168368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_14243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_171672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_56396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1755.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_141324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13098.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_131834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129597.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_173082.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213650.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_190307.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_19869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36455.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_4327.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198526.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13555.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_19358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211775.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148688.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_169491.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_128026.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142691.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149595.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_180485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_111934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136875.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_51464.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216394.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_176586.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_40907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_171842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204685.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36229.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_122006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_188452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74732.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_128533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21489.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_145982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_217348.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12770.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_139272.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_9374.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_78803.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_62447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_190186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70636.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96791.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_150523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211708.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_165682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_64042.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_147364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_7603.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_217139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_191207.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123427.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121722.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_78662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_83210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_183311.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_194605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26457.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_150503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_67184.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_208124.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144283.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148560.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97184.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_19960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45274.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177252.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_71920.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_60129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_164882.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110075.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86244.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117775.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189912.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148486.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186380.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166365.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_51686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182072.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_31392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137256.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_205391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_66282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_82960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166970.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97776.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_214529.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_112139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_69772.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_165513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_215921.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196633.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_126856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_214328.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_165315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210999.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_66339.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_52307.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_40633.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_171986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_103488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_119811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132544.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_128315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134597.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_78523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_37774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123589.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_181613.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39760.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86704.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29750.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_168637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42680.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_163490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_140892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_140744.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_112119.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_34285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_190387.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_73988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_111807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53202.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_171925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_100284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_23465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_7083.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105426.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209431.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108424.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_150011.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95568.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211914.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_103986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86306.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_190990.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_46313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_56402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_125878.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_92130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_10255.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_41195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45454.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146352.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_165107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_14276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_188741.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_73878.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_18036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_217270.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24955.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_167523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_50710.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_152009.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133714.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25280.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3320.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209568.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_78922.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_201384.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26678.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12687.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_56188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_19826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_34048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_140364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_78900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_128823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_185506.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_23241.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_185469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_131756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49871.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192208.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120408.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_28692.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_163332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_28804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24492.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91595.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148833.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_139326.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154335.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110119.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_5641.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99438.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97742.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_141928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_52482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199874.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48041.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_84504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_160314.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166425.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105007.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_128962.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_185409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2816.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35328.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_4878.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_124059.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_152487.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86528.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_14810.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85901.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216641.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24882.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102577.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_28543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_14443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210848.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146066.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96476.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_54948.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174372.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_71206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_119530.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79132.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85236.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_78743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155800.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_52747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_126868.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_165028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_208792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3961.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_54898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195489.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53222.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_15208.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_168139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_147620.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_63872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118355.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138992.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_152926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_165288.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_83443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17921.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_103677.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196945.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_151598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_215179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209676.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55536.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58627.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_81871.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_103218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30562.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_171645.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38859.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_173963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_125361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21259.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_4249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107808.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_145050.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_194593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22208.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_160676.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_66722.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_46867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_23617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_244.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_145092.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_185744.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_215021.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_172559.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_145144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_50780.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_37130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_9264.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123741.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162945.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98216.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_31870.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_168132.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29841.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_90157.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166204.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182352.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_18875.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116447.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_66419.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3556.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143597.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_54758.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213175.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_60665.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146969.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_125835.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_201993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_214608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204419.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99162.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_156703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8568.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80530.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_19412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134229.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_64918.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129155.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_201887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94849.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91060.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99833.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174148.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_59667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182487.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_126403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_124187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_34623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30671.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91648.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_90653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210770.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211970.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118572.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_167692.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108295.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_139857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87098.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206933.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110862.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_56143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202781.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_200523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_141937.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_200387.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_92231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_33483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_92394.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21781.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174082.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_168455.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_62636.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_194169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_104798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_82399.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_61343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_165999.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_205976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213621.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_113267.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105627.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77655.qa.bqv
