/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig178086.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig38263.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig133467.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig285744.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig20364.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig6109.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig118759.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig46195.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig63055.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig236900.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig39668.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig139389.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig98022.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig60667.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig170183.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig43689.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig224163.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig136619.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig26708.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig11275.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig207878.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig216797.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig8306.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig96325.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig72005.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig152332.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig186989.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig11397.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig49134.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig236681.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig94291.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig49012.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig282314.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig19633.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig248772.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig102718.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig201520.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig52225.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig220558.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig163231.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig10508.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig49874.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig184210.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig46802.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig181514.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig58925.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig211061.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig178155.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig144375.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig153866.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig112182.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig276443.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig195068.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig36298.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig103492.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig192876.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig86419.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig271248.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig78495.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig161535.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig133410.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig54403.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig161631.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig214362.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig185838.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig61586.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig274870.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig248088.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28175.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig287816.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig58288.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig109761.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig164804.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig223086.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig220091.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig61550.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig156164.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig154404.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig223097.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig59678.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig253176.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig252499.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig25425.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig181341.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig213857.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig139683.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig33738.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig240429.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig59911.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig27891.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig12815.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig196871.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig179821.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig193787.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig102821.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig201476.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig261968.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig78744.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig34388.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig108940.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig29883.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig106436.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig104243.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig19494.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig202275.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig153110.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig166429.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig14275.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig234055.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig44182.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig289763.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig173664.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig30069.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig84942.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig158940.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig87742.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig199018.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig88938.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig63740.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig26643.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig48816.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig18841.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig295110.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig81332.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig73220.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig175117.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig144507.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig90888.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig183976.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig75973.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig185804.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig52019.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig200166.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig102261.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig280777.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig27801.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig140369.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig213940.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig284854.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28006.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig176887.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig144595.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig196293.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig114880.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig31583.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig285676.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig40809.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig69034.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig83912.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig265238.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig160707.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig209351.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig94273.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig106563.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig263083.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig177726.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig31066.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig30432.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig112134.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig82301.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig35341.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig275078.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig85988.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig25006.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig14644.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig15973.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig252600.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig288056.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig258728.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig167598.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig37039.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig76259.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig74358.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig38104.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig98389.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig198930.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig235802.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig99627.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig35152.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig25596.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig145499.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig176656.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig261320.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig249682.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig128342.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig285888.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig173538.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig291198.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig40998.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig11515.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig81532.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig4977.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig8756.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig178799.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig235953.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig264451.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig137241.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig130763.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig25275.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig26386.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig273282.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig25831.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig160209.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig15545.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig81436.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig193984.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig175170.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig193277.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig39865.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Ultra648.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig247503.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig153109.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig260704.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig89032.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig224662.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig288700.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig106269.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig138846.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig34289.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig126186.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig277095.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig226278.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig59503.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig259229.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig31150.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig257746.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig41739.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig129782.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig42912.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig8701.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig179692.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig25951.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig106161.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig167793.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig243851.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig53160.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig94102.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig96097.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig216685.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig162294.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig230531.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig52869.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig189372.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig138467.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig220765.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig223465.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig157063.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig159350.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig186486.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig234200.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig24770.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig111387.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig185055.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig125697.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig32948.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig191141.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig35048.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig13717.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig90542.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig92262.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig89157.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig128524.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig66912.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig91998.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig217718.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig241244.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig71371.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig15335.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig27651.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig87608.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig37726.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig89236.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig37364.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28090.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig161896.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig51576.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig268243.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig285569.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig146025.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig145533.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig141881.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig279408.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig32444.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig27998.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig206735.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig211131.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig119260.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig83221.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig143989.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig177795.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig246524.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig131430.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig188473.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig59686.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig62637.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig261783.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig32555.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig69954.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig175907.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig96221.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig187816.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig159935.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig9493.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig143624.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig247835.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig63027.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig139507.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig127415.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig162864.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig187484.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig33016.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig215048.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig90648.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig169517.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig284451.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig174093.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig42981.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig213038.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig35452.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig27950.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig193292.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig73757.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig210930.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig29858.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig5853.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig239410.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig143178.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig207474.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig206975.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig143500.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig275892.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig237535.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig274974.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig148602.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig275012.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig121957.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Ultra153.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig42166.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig266304.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig214314.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig155914.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig83747.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig145107.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig123514.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig56388.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig44411.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig95528.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig162465.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig80910.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig32453.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig41373.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig270183.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig179660.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig163797.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig57556.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig291384.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig90893.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig101110.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig196410.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig34055.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig98851.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig174918.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig278953.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig133942.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig47561.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig43544.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig19092.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig169910.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig120421.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig69362.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig152166.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig289146.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig10853.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig45085.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig62401.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig216879.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig185525.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig1876.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig191351.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig295327.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig195884.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig12746.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig73679.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig261352.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig159275.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig291156.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig187381.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig85408.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig24219.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig195032.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig257977.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig292730.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig179469.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Ultra65.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig33241.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig135961.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig213592.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig171311.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig233368.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig152411.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig75642.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig44312.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig36962.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig38837.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig116372.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig141587.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig8886.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig15808.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig249514.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig289522.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig69110.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig241506.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig187640.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig203407.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig225539.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig136463.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig216116.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig46266.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig184089.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig101649.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig82973.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig10365.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig193404.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig36028.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig123230.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig119933.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig9221.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig123036.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig185049.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig199347.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig114006.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig7537.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig185791.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig109864.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig166999.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig274686.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig36085.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig254617.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig95918.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig193160.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig240667.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig118384.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig113485.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig70132.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig158559.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig280911.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig226679.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig269956.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig18227.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig27520.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig260600.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig143329.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig185116.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig202820.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig120103.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig254911.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig249655.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig11468.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig176221.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig86428.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig13996.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig39096.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig186372.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig78048.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig54235.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig6118.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig94466.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig223447.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig76735.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig130071.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig290495.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig120380.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig275512.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig187176.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig52310.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig197945.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig211059.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig256882.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig48525.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig25230.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig17433.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig210958.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig91224.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig214072.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig97934.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig127900.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig78367.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig18263.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig268093.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig174559.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig280558.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig231839.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig144145.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig30389.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig99073.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig181793.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig23772.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig38795.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig289882.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig119309.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig275741.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig75124.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig184353.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig223209.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig172373.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig134826.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig31330.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28257.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig150127.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig108014.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig131336.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig111524.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig33422.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig112196.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig39902.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig5372.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig232200.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig229205.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig104359.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig57206.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig234824.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig245250.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Ultra123.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig7153.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig131374.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig47507.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig242106.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig241165.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig176704.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig90278.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig126145.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig99459.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig106444.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig112540.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig37221.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig235702.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig235611.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig188523.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig278076.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig27134.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig88036.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig60192.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig274982.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig210446.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig178472.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig20221.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig25449.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig38368.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig44214.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig9880.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig241690.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig42167.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig284471.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig241460.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig227111.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig114577.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig22236.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig35964.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig99025.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig146452.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig34029.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig246360.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig56576.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig134635.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig122607.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig223403.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig294367.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig22327.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig190052.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig261659.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig47454.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig207979.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig281499.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig180087.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig147576.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig202547.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig21333.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig36006.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig268858.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig235527.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig184125.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig116381.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig193832.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig40946.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig199880.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig255402.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig8801.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig230641.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig171556.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig186267.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig14781.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig281617.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig15068.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig13377.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig146388.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig277942.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig62140.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig83451.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig238969.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig103620.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig34542.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig20620.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig53848.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig123563.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig188878.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig171911.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig46089.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig200543.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig49731.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig13174.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig174439.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig96494.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig265657.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig271315.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig243450.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig51789.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig256140.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig284430.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig4744.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig212325.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig19641.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig92291.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig60780.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig214900.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig32887.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig158425.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig30675.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig24222.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig68501.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig12888.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig40035.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig11597.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig80746.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig245965.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig71229.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig172916.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig238790.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig68389.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig5521.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig224377.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig94206.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig203339.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig163172.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig18809.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig267394.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig126697.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig44430.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig60051.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig263453.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig209139.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig80869.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig186565.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig1929.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig99969.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig154672.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig248790.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig22888.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig274416.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig11902.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig192129.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig76316.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig82623.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig98879.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig73068.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig35706.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig132406.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig102699.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig58446.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig15266.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig86472.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig42397.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig206502.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig61603.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig24523.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig256826.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig27727.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig85677.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig122291.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig149690.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig224600.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig81104.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig18302.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig151990.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig190777.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig66309.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig213953.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig84499.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig202830.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig112634.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig294763.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig71402.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig184165.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig74239.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig68490.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig293843.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig90107.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig53118.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig39804.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig29489.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig162723.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig138465.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig253558.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig231380.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig169640.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig132182.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig109257.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig186467.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig15780.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig25794.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig91680.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig115439.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig204467.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig187228.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig233856.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig229185.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig109111.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig222990.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig24460.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig196076.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig52083.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig24608.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig196807.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig149583.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig128087.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig52438.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig152974.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig36887.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig44417.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig17249.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig239936.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig64700.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig131219.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig218750.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig127379.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig224857.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig244996.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28977.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig37805.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig21212.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig249980.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig233149.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig184928.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig128566.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig190469.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig223484.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig215554.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig16457.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig114867.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig229316.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig126273.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig273173.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig117261.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig274618.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig27200.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig192368.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig201383.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig291135.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig47287.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig212730.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig21323.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig15128.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig38589.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig242484.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig286064.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig266617.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig62398.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig18004.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig47525.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig144086.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig184512.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig191253.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig42221.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig143270.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig146891.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig115874.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig5074.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig271480.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig36670.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig162704.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig186527.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig149870.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig131021.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig82621.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig234291.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig15250.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig270603.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig119492.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig160733.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig205524.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig276416.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig61119.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig235395.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig51888.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig200290.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig101072.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig184070.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig119573.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig4093.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig184756.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig91112.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig215902.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig43013.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig7053.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig156540.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig223814.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig221017.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig19472.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig6187.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig244019.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig159150.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig30634.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig257045.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28864.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig269076.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig196962.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig262248.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig169639.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig3794.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig52415.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig114363.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig174597.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig136853.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig172947.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig93827.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig31496.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig268521.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig42867.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig45860.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig176506.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig53508.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig22924.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig251596.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig175256.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig40075.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig122025.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig221506.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig200913.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig189312.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig3966.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig8597.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig146137.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig222407.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig61290.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig284755.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig91729.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig153379.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig144819.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig264498.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig12371.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig43617.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig57460.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig8123.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig140876.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig17620.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig101463.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig293522.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig124726.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig7813.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig20964.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig280036.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig29249.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig19466.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig152922.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig36501.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig147414.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig17501.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig247765.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig24304.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig92147.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig65537.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig117537.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig149385.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig187958.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig270540.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig90250.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig60738.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig88960.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig260506.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig232497.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig172863.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig143151.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig285229.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig212875.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig92526.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig148524.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig19710.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig212110.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig101077.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig155329.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig234525.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig100273.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig134642.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig187057.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig62312.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig182887.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig219298.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig93139.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig91144.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig172457.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig249369.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig154776.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig3952.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig256671.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig63568.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig34968.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig194336.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig170902.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig46814.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig280649.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig179156.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig190984.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig29453.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig74348.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig64992.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig49661.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig203947.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig174930.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig151991.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig61007.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig90350.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig67689.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig107232.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig261251.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig65981.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig97443.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig35262.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig35672.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig11359.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig171503.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig222396.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig22621.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig103695.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig21590.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig36607.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig181609.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig206262.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig185909.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig242801.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig235552.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig177321.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig189960.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig50548.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig168953.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig119117.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig225957.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig91916.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig230747.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig177272.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig129041.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig144136.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig161087.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig114723.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig239711.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig285231.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28579.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig140641.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig184462.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig141120.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig229974.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig50343.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig19620.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig240771.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig69996.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig213913.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig63644.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig53849.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig38151.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig293752.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig160746.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig23787.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig137221.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig8728.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig236602.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig259919.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig287402.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig194999.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig42627.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig90132.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig200306.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig66710.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig94495.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig115032.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig271760.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig18434.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig135375.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig132826.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig183686.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28411.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig173286.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig30172.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig13408.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig290372.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig57968.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig235954.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig164473.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig204407.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig185313.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig241163.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig228301.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig184495.fa.out
