/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189555.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig163684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig194968.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig256564.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig68157.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig91300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159275.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191541.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig116322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig93068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig221606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig49301.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig256735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig98660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig228485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig195918.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117704.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig180344.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig233043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155767.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig129260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig263149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig55196.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig79368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig230892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig198110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig224513.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig193751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig49985.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243031.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig197963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig261088.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig81014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig219126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271155.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202802.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43738.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig114980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283042.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig45585.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4191.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14113.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig259100.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig289497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig273341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig67407.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23688.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9813.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig234179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267394.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig278618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig33765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig114126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21973.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21875.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig64403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig48972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig252797.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig171828.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig207714.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig226904.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14685.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig114808.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig151063.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig201416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig84567.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig78976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig136894.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig167051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61549.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig233163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284633.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig2442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig66233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig175997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig91864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27141.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig259111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig151136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig127462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig106895.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig230221.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig74182.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig154945.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig270555.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig3490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig127169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig225264.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41019.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig77254.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig26003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283238.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293876.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig204951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig265069.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig87033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13758.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig65548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264648.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig217931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig154629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241973.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig101044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig236457.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig112550.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig121169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig83650.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143862.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig90980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30878.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243080.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162080.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111963.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig33629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118886.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig110866.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig167467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig263166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162764.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig215648.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig182457.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292749.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig160537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223575.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162742.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig100656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig236995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig201035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10457.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig136510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig209578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig224321.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig259351.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig207586.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18547.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig120530.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47160.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig275154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115306.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig227124.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig107247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig258788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145821.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213808.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53665.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig164035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145071.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145881.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig195321.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig164335.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125742.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig194993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig95364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra724.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184716.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283471.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35687.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig175010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290336.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11870.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig236156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47119.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig88896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig77712.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51508.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig148731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig225393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig76935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125114.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig90449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig33576.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36613.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235399.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig227950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig102395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig233154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133273.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig154117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22367.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig195377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig234386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig179096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig218523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43800.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig201125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig194987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig274711.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57629.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig207053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig141524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig112600.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig276079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig116302.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig62779.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig64560.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig207332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246024.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig214689.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig232392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292505.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig268468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294191.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264261.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260576.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig196699.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig102993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237182.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17776.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig124465.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19579.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99770.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131487.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig129509.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32256.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig253843.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig212431.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig33631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig161419.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271762.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig291255.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig266887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146775.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig171577.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143663.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig126443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70813.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153836.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig73046.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig255435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig207055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig193660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54369.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra312.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig167052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig176260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig130411.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146550.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig52715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig68390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig169349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig255303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149992.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig140490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32669.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig196481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig224200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135440.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig89665.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig66573.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig82552.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig173113.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig89159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58932.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40028.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig221206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170077.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283969.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156399.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig257400.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig291057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra93.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig258459.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186871.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig60316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig123787.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig164248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162144.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig122005.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig214560.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig152839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig169959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig255049.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285843.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig139867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220182.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig77560.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig295196.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57920.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig98233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig252591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig268556.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig122708.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig212213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig96221.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132005.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35695.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig108408.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig193610.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43711.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig79297.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig169402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig98628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184592.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104307.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig81181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153802.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig203474.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187474.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117146.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig289223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig89054.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig287941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig96157.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig233025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40698.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220843.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig112090.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig219279.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig26262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig87396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig92107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17211.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132273.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig129434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig227033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig181269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig122699.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig160928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75279.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig74659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig76122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig221683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig226323.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28211.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig64349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170905.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig240173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104818.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig252107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig126996.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig116795.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig137248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig74551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig195668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103690.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13912.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118518.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig80674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig59526.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig85830.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig65222.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig212167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig224023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig173325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig181080.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43757.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig93511.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125340.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig136089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155425.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig116883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239433.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig73820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279818.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig116262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153557.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149886.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig48591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43849.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243564.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138866.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig49888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig82523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig263656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig46164.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29886.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig77751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig269238.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig275149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150763.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig261876.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig134090.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig194302.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig193951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig154976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig196798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig278750.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70298.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig272348.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig196463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283858.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8320.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig227070.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig157055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27001.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293354.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig163217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig139448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig89784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig3246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14189.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig278419.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig251586.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11722.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290444.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig261364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig193395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig230468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34923.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig68975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168426.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig82774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig268787.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig98282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig265025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig123611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig233640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig232396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43677.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162026.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21758.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44228.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig262143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig272362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig151022.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig142361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig134819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292661.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig222423.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig224745.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig100338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168506.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig200224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213277.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135860.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147310.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24541.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig234568.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig112909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290191.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig205930.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58337.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8054.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig200546.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig129660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168868.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135633.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig81688.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig136935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig164096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig158876.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig49578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig141156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig245446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig65154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig248134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig164210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156160.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235396.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig261352.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113871.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189748.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig62946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig289294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig281960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig63202.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig270886.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig245623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig83504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig122618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189135.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig175206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155021.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig195864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig175757.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig60440.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131132.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig209685.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig127343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig49232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig120933.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202264.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig83385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig106301.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig93533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig247002.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10557.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290914.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig33012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8155.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig275423.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig114191.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig277407.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44897.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25957.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig100380.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149807.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig139903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34522.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51431.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig180565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig88235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293219.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig291239.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig134355.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig273740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig292283.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202002.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig108988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig212704.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig263737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig180905.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285567.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57882.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig65393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig76956.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig148203.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig167415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig92532.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig107391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14009.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125777.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig215183.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109918.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24026.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig59721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig227876.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig121110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig101009.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig74248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig269324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138758.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig88633.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125766.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig164949.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig52832.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig160196.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28993.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig33652.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115029.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285509.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig157206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig221003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig215649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig66398.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig128712.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig281499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig79006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig134683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig76679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271770.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig106623.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig105420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig82798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119475.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69830.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188250.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149511.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig207647.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188687.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118407.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29871.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig176401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig176834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig211669.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig268427.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig52592.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig105278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187162.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig248743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig182977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig127577.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig154785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61567.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271651.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig230252.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra506.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig140695.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig197435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig230111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138590.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig226194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187021.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244808.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig177032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig64271.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig97664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig177502.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig194523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187625.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig81477.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig114552.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig254563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25672.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig62597.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig273625.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210022.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig90266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig169418.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig171419.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50990.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202059.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190680.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig52746.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig204744.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155956.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig169420.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig83271.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig88543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig231089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig263468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig120956.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig208383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig123086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig274043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig291684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig245957.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239922.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig174801.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig287200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig597.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132239.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig169618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99841.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig52601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4742.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186517.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig62488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246459.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202784.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig195383.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig62034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig101043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184388.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44777.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig209953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig108439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189453.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111992.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig120021.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig247140.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235911.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig151338.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125526.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig88619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280256.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig167282.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig232251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig295286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig56989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig270890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig59997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131258.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig221960.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237487.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig129236.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig86811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig67120.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig171384.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig222266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig200067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17804.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig46266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34529.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig49929.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig192307.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig84544.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig177443.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186425.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig93775.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57091.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig198294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223912.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30385.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288622.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig228732.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235043.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig197999.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig88930.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig62268.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165419.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4559.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig216377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig122727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig81217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241506.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig98772.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig74034.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig258992.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig166846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig68973.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10024.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32295.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig198668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig151763.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5046.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig128789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig108067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig225826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig77548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig225392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig91029.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271001.qa.bqv
