/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250555.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig137886.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig172451.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165197.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig276953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig249998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24020.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111489.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig79216.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig245437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig128511.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig181579.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig87010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig127094.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig77599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284641.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig274508.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32528.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig101168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71761.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig107445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35422.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286300.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13464.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig171955.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223537.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig59932.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7562.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42486.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213081.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig281533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150812.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig249087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig173871.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig134110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig183469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109031.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111962.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig92737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57174.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig99628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31838.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6690.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig248908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig129456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig200974.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199207.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36732.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig247421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188471.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig206291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig105902.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig196895.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237677.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig194945.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig167977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243726.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig171965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig198855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294861.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15124.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig200013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig216657.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig100562.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig229316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5696.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70638.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig110304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig259516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig48961.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig160969.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24805.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig274603.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig236818.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig85417.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig201150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig33390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig256089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig82363.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47750.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig59316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig100176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig130933.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig86600.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig224980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146521.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig281271.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig55203.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69549.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig52924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34380.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig108198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig112063.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig127023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig154573.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig247653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig227273.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185073.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162356.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288556.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig242777.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig100056.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig245557.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138538.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8601.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig265699.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig161143.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131875.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig209618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig278347.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig134504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig136673.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig88270.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig56315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig166543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig226159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133418.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51706.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig201367.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238665.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24719.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig183779.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20280.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig251653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig91792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig266168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig215212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125245.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237795.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28024.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig269896.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig194581.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig193630.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig261223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig183983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223235.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4244.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238407.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig198979.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig141438.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig258660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig207305.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig206530.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39180.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig249461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70781.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig106575.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig139823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6704.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig88611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188920.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47308.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig129182.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig172160.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264509.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69933.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig194512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig139413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143681.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293207.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13716.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50454.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig33987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131989.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig90432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig173055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig287635.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32411.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig173039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig192893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig84782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145103.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264802.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153259.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig256192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig205166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig289743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig109283.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig11727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig291295.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138703.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig91147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184934.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig258106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61327.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111968.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig68241.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig273320.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17146.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig105188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig177251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig96517.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61175.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig171258.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15918.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig204049.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103090.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig151122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig161925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig44745.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig129514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig89925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig124319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig124021.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig68705.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig173566.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig201319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241411.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig85539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig83662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig252433.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186815.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30840.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig68724.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig90293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50088.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246684.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig85694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27603.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig108798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig211854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig110232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig88561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig262643.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39777.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig157540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig94885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig254210.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig205436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig130699.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75015.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61293.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig83636.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19183.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig269822.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig33078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig65425.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271917.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138914.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig224117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig26578.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig93990.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig92055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18468.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284061.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41273.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig242583.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig253889.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246346.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16652.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig163694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig183280.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig123050.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47118.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig249242.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223347.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig228657.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig196501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig156914.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig60834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15635.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118222.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238871.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187222.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig205013.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig114992.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20008.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig107362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig206251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133613.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4076.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig106984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig45005.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig275027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig278428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig216335.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188196.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig136486.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104850.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig171891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig207205.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig232939.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38574.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41698.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38777.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig37009.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig266218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223719.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig26638.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133261.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143658.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig180971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig82243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150692.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244464.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig157767.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig152545.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53476.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig211813.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32474.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig131997.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig287666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig214691.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238635.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig232571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig256550.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig56743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243494.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig255453.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294938.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig219192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260651.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig157751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51274.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig148470.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133830.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig287440.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig62150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138054.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig46176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig252273.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig37596.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153263.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145436.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47305.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig251331.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig140932.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig282249.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig215607.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig87120.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig246978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig59806.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig57580.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187526.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig128239.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig248771.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig138150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267652.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig66343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235203.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig143496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig124912.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig167527.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig289567.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5858.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig37045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig128743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15418.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32494.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig148336.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig172992.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135852.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig289972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig236361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162613.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig80533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig197289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271302.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig232644.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig127676.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig74101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig45550.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig247078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29494.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23641.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig270654.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig159153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig134392.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig52344.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig145825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283833.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig200619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig171915.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig152595.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260564.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288806.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig255792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig49864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71376.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig92325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69529.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig140004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig86588.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig221019.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285508.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig95648.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig86599.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig179393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig260573.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig80175.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig270397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54133.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig126984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72958.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10528.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig269493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig197463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig289731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig258554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig177109.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig207343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig263877.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10750.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig45225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190453.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig166485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig242756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig263222.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178873.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70833.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig215027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig252864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23491.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig147785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153023.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133780.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig2715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig140474.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig134949.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12172.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig135131.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig115499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47653.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104091.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58567.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig254388.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig55231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig81915.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig113275.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig77632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig51634.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig146519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21145.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig80005.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig201770.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig5576.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig92531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104562.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213552.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig195886.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig263933.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig120150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig206615.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig26766.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig281640.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig229874.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig175655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28456.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig90025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig48867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig121315.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig248533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig265705.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig144660.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153968.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig219876.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10903.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig270892.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244433.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig263501.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig192296.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117906.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig66000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig274066.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191026.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig17171.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig174544.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig148257.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig271727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig45375.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig174053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig204349.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig59862.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig180122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig288377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig222111.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39372.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig25435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig66068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213301.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36567.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig235173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig233644.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202203.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71277.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69754.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig152702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig228650.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig204408.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig196169.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264592.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42155.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig227749.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig102849.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54545.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig231364.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig65561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig290269.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27536.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70528.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186659.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig160840.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig202880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig103770.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig76737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig54352.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig137565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig102397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293720.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig269534.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig46099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284366.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig181054.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig201577.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig2612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig158932.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig191384.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig214209.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig232129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig96498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig56217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10972.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig270636.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29503.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig196693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig126565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig164470.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig164227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig264697.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294517.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170839.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig220002.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig13687.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237424.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185421.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280055.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig126155.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168733.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig256774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig208429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig183774.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig209602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125970.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig94683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32893.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig228482.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra379.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig157153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig77095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig199343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig262446.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig101836.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig134806.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig281078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig114792.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig40721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig79605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig275870.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig275313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133092.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig176732.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig239065.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig74955.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig76154.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165370.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig107920.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184353.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig110217.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig89038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42068.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189466.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119767.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig68495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig247397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig136952.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig120532.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig291066.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8163.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig108335.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28181.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig221189.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178071.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig163617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig97924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig142551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig142674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig234382.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig242410.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6275.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig210048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig229951.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig117948.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig281133.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig120307.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig43941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig8128.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22525.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig125086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig285554.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72671.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39535.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig181000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118112.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig257611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig277309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20002.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig12444.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig244318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig31834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig293850.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig258299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig133931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig49964.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig141788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig121509.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig65286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35095.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig71941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283180.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig58327.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig21228.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig18114.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig281378.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig176242.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig102750.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig16365.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig91644.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig253231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig214334.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig127740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig112053.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig265766.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig278481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig35351.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig62071.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238562.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig87939.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig56682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig223916.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig179054.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig198183.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38881.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig52455.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190764.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig33740.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig98262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig283265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69557.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig236450.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig203348.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig68266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig277116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig47980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig26312.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig34681.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig178018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Ultra114.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig30756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig45258.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig80208.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig218915.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104490.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig10373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig72107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig170050.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig110661.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig134635.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig242998.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig150316.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig261333.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig213982.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig211713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig187842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig67874.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig116078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig114110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig120252.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20380.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig189535.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig279768.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig119682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig6238.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig22912.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig53737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig49120.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig37409.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig160690.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig242152.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig294051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig104386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig259165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig248047.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig82186.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig277430.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig62473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50295.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig148125.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig165681.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig221699.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig61288.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig255263.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig70679.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig193568.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig14445.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig240744.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig23348.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig203543.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig185949.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188202.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38048.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig247837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig161203.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig123187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280966.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig4086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig201675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig251711.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig286802.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig289856.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41604.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig225428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig188011.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280438.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig48519.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig171692.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig19611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig94464.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9967.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig162033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig280150.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig166096.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig73357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig149641.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig50345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig237104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig254533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig95302.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig181453.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig179314.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig163309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig181748.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig211328.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig241750.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig7268.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig39136.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig41593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig27128.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig75228.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig137295.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig238508.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig284881.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig111358.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig250437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig42625.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig24377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig20887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig100591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig37286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig155485.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig92018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig65928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig38027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig207837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig29310.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig118734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig28935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig267227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig153664.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig9391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig186882.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig168397.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig190176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig222253.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig36306.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig15977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig243504.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig32329.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig184060.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig69968.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/ornAna1/quality_scores/Contig132009.qa.bqv
