/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig166464.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig212981.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig166562.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig113820.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig103166.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig232797.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig130116.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig170186.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig73340.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig124810.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig286707.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig65255.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig212954.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig38076.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig175020.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig237177.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig84847.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig290957.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig200551.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig159022.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig224906.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig226126.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig47955.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig273677.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig168655.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig31735.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig183228.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig59088.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig40568.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig217147.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig239788.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig83683.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig89473.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig281407.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig139556.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig39392.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28154.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig180705.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig12103.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig223770.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig183611.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig185467.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig255659.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig171824.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig72446.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig6006.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig285052.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig60096.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig93672.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig69505.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig233659.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig118089.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig46844.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig103652.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig64306.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig147523.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig57276.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig30711.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig16837.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig280950.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig258669.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig156516.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig27519.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig200629.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig26764.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig237910.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig247206.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig287711.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig104822.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig151935.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig130566.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig208512.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig151820.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig64174.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig43989.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig21290.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig184969.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig125287.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig197315.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig283942.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig164682.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig274162.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig93764.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig34195.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28125.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig10592.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig168052.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig107888.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig241659.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig26421.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig149025.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig113295.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig15314.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig171298.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig13857.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig83737.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig207109.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig39842.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig102918.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig19301.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig14442.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig292799.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig84172.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig200720.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig24259.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig191134.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig15182.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig181306.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig158794.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig240069.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig186564.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig283283.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig23843.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig194673.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig103075.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig74662.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig116649.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig57412.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig111384.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig202073.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig136141.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig173304.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig72605.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig207217.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig159776.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig154979.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig30479.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig74900.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig26310.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig158198.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig190185.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28195.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig198632.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig238325.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig289286.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig189674.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig233810.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig180654.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig30864.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig99567.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig233083.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig210650.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig293914.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig1718.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig47782.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig67064.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig81286.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig143649.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig99752.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig78727.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig18707.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig36939.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig217897.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig53928.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig65924.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig294872.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig176353.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig223596.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig43208.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig19253.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig121685.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig52370.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig236518.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig116292.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig288206.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig83153.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig284724.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig102002.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig65691.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig177692.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig205961.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig36910.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig45327.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig262312.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig179091.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig26834.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig32440.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig269213.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig230881.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig286909.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig262102.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig48857.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig184422.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig42657.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig127995.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig41340.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig56385.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig285347.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig214608.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig52275.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig150952.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig32259.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig143808.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig111080.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig35162.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig38116.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig250528.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig2582.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig263637.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig50699.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig5052.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig116221.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig67000.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig159410.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig47274.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig126285.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig281079.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig117387.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig55377.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig203551.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig84523.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Ultra145.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig259279.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig5007.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig20492.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig242252.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig136990.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig246348.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig289834.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig108419.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig22786.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig185452.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig35267.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig146939.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig210085.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig94924.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Ultra251.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig87442.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig23498.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig179364.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig48702.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig110470.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig111499.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig288213.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig146104.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig104386.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig182634.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig39885.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig105393.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig192784.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig242474.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig164404.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig33534.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig120711.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig285224.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28508.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig156088.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig245218.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig91676.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig163374.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig42578.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig67524.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig41149.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig217309.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig160259.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig43508.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig264737.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig277634.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig189701.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig268446.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig241678.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig19100.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig24514.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig262990.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig21019.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig89943.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig84238.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig184560.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig11493.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig132865.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig72510.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig6005.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig185593.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig288557.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig162068.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig45888.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig146141.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig223786.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig112487.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig43795.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig4812.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig182503.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig180170.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig293696.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig245195.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig24468.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig184881.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig38332.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig182943.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig230873.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig80407.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig117594.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig129290.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig37380.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig187517.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig237697.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig229778.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig64198.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig113419.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig134508.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig12834.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig26652.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig113140.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig23092.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig214552.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig5483.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig167931.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig253698.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig29524.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig165223.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig167313.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig280470.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig253706.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig96385.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig46622.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig186993.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig26803.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig102566.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig102343.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig187592.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig69913.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig200188.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig276418.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig24327.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig90537.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig32278.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig242325.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig165749.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig198141.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig230535.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig5398.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig258540.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig5412.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig112474.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig160186.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig284710.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig11442.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig157627.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig170410.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig280079.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig112015.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig96646.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig190933.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig13401.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig48428.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig10714.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig290719.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig32094.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig67090.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig40468.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig27769.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig63673.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig259519.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig45468.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig175229.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig238350.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig293073.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig66901.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig131837.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig202336.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig270745.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig190857.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig155557.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig51226.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig6340.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig46298.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig168235.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig284143.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig227425.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig113729.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig12748.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig16686.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig16336.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig53312.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig259588.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig30908.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig72744.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig49703.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig77517.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig98562.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig137110.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig292079.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig108337.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig251390.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig186593.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Ultra758.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig247029.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig277006.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig224191.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig86161.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig207904.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig211301.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig266554.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig44909.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig291351.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig291413.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig36171.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig243270.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig64482.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig17891.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig137043.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig55768.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig276253.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig203031.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig187111.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig80050.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig212880.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig51112.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig211394.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig83399.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig155269.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig38630.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig218219.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig116770.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig174409.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig236550.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig144266.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig242939.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig4205.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig61745.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig108309.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig23158.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig73878.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig186696.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig41064.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig19680.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig285211.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig34814.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig12325.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig221483.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig272731.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig133790.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28749.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig32380.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig162220.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig172752.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig228768.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig286308.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig141405.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig179276.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig276532.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig284410.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig114826.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig226377.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig60917.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig290025.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig31620.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig37629.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig96790.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig38842.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig75754.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig260914.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig293602.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig227843.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig216673.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig201424.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig48997.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig166380.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig45400.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig5901.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig166424.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig233845.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig5415.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig122329.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig26674.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig194267.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig95142.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig50647.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig73385.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig12784.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig60179.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig143284.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig15061.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig246744.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig7770.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig52405.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig188855.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig109839.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig182390.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig171083.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig16672.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig230058.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig25171.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig10708.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig229952.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig65515.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig199352.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig167287.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig110830.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig22781.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig190022.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig243903.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig140309.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig271780.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig220052.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig58992.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig193469.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig155003.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig29127.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig86974.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig5705.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig31752.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig139136.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig112509.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig20120.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig88010.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig136012.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig158757.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig182889.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig274285.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig13084.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig26645.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig5242.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig217143.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig154543.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig208104.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig259350.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig258024.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig67479.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig13996.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig3745.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig187550.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig59777.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig50277.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig62506.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig100916.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig43567.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig163784.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig220526.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig120319.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig78483.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig242633.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig20488.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig82776.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig22750.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig88781.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig7757.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig218115.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28994.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig42391.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig43844.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig167610.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig148441.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig153938.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig5195.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig75566.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig41564.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig195002.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig246106.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig125843.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig144796.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig240348.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig138535.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig115502.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig200383.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig61635.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig54947.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig206986.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig227115.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig86947.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig62634.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig276983.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig283095.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig289910.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig225864.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig268968.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig268462.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig118985.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig67827.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig263565.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig125563.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig30099.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig231249.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig119323.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig166206.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig72920.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig280825.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig97664.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig11717.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig226843.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig13728.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig229743.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig257649.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig86390.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig253839.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig118419.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig61340.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig206170.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig8501.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig237012.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig176547.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig12063.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig30727.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig80725.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig39048.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig45069.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig72103.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig138894.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig236699.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig51062.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig183738.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig190120.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig106051.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig163382.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig235036.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig150133.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig249945.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig222378.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig94024.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig163882.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig187878.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig168538.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig53982.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig39888.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig45438.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig41483.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig164870.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig6402.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig38666.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig125788.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig138826.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28437.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig295214.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig38027.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig52490.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig229402.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig203569.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig285812.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig218514.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig73328.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig161854.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig3125.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig31927.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig61681.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig25824.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig270444.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig60737.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig145326.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig34797.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig25154.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig129436.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig268047.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig285133.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig85602.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig169899.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig180369.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig259297.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig70256.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig177666.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig50010.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Ultra700.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig123908.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig242428.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig247992.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig120025.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig43252.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig166568.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig228569.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig24950.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig53981.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig52128.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig203721.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig216814.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig173699.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig61993.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig260543.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig150372.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig217861.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig53386.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig97352.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig120521.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig90703.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig31077.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig98722.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig241927.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig284466.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig71274.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig107803.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig43252.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig199798.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig110228.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig54080.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig169098.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig60545.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig111040.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig125078.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig46943.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig169779.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig290542.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig68374.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig19293.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig110677.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig135916.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig278622.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig13055.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig145170.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig31713.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig193444.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig270482.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig165196.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig103398.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig273610.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig37858.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig147775.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig44536.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig32686.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig47589.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig173216.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig172852.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig150394.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig208729.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig73529.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Ultra632.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig68846.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig16050.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig23871.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig79474.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig211930.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig158754.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig15568.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig241072.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig74710.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig118670.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig29721.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig290372.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig88172.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig30295.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig282754.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig72876.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig242944.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig237167.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig159976.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig39529.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig94624.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig17880.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig52828.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig195899.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig45601.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig32525.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig180109.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig6654.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig186525.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28238.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig113551.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig33672.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig113023.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig248245.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig187415.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig48146.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig25624.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig183591.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig131593.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig170378.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig155205.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig110504.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig25795.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig104426.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig61390.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig290877.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig280191.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig3770.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig251048.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig146378.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig43909.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig221089.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig114714.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig102839.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig279449.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig32289.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig97383.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig253049.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig150424.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig283969.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig32358.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig56823.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig31563.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig16358.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28464.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig108074.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig185358.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig231334.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig7185.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig233752.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig116584.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig249385.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig196129.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig42761.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig174843.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig70238.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig143571.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig63285.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig284402.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig25493.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Ultra28.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig113229.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig100149.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig77984.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig275918.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig12572.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig211074.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig39128.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig284318.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig44000.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig62575.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig13818.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig288802.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig34990.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig21166.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig278437.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig49767.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig286717.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig264698.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig256669.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig237051.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig5557.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig83739.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig236695.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig95414.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig40671.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig16679.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig290011.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig137083.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig191785.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig278283.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig162182.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig48510.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig279846.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig290636.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig230145.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig206808.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig33929.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig247141.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig113806.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig4047.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig236341.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig65515.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig21773.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig111760.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig153793.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig118922.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig228001.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig277868.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig139113.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig196287.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig23249.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig282118.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig228123.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig106300.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig203034.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig184961.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig5104.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig102340.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig124051.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig39564.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig16740.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig191017.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig160817.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig73088.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig217540.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig254998.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig35957.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig168425.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig53347.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig223898.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig174207.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig37944.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig70895.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig246108.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig273011.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig19898.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig244325.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig263983.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig80759.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig72470.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig170203.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig217026.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig55556.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig208342.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig127368.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig165192.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig79234.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig106329.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig57086.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig11565.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig114108.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig200509.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig124117.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig114122.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig30334.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig223883.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig132121.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig172369.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig200158.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig279698.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig247691.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig153229.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig190307.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig286286.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig114897.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig122810.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig284874.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig141333.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig152191.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig25328.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig238294.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig279689.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig38861.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig280485.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig155952.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig272248.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig59622.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig286529.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig34470.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig7070.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig41477.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig211056.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig26655.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig70683.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig16336.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig2757.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig239842.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig5058.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig148107.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig291800.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig284539.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig28173.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig24926.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig67168.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig199323.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig30204.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig23670.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig214795.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig231386.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig102591.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig279729.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig287116.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig293059.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig32042.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig167659.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig151276.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig108677.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig197090.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig38208.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig145479.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig105245.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig287279.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig121917.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig3265.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig42491.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig218916.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig186947.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig190891.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig79045.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig22887.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig46378.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig40941.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig160287.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig220789.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig51457.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig190213.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig47591.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig283102.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig294018.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig236068.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig220752.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig136896.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig256624.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig289581.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig9435.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig8140.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig244219.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig81410.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig246793.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig241291.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig134988.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig250508.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig42386.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig290764.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig217797.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig113745.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig254990.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig25106.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig183114.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig135704.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig166715.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig123461.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig52033.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig215619.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig13887.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig278672.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig36917.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig63578.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig95577.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig49006.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig203959.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig67600.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig276040.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig12107.fa.out
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig218724.fa.align
/cvmfs/data.galaxyproject.org/byhand/ornAna1/rmsk/Contig213657.fa.out
