/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_145990.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137869.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94666.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_160539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_111796.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182416.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193530.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_125898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_5606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149020.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95941.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123707.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94992.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_63927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57943.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210388.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_112124.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36872.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_176098.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99242.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212360.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114418.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154723.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_203900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93834.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16175.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_164277.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_150119.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116258.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101523.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_153649.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_111328.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178461.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93797.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26146.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_151390.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186221.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_217500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121884.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_103148.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_81208.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_89820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_63671.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57343.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133319.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58336.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170861.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_18702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_103662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75179.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149202.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_73745.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_119294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114877.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_176527.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162667.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_125449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_43075.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107294.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_50211.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_171203.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213405.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_194123.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187789.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_141020.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_40914.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_89916.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_185959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_62973.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182700.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_168682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162769.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_56418.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197072.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6597.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32509.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195577.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_171859.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_181031.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_194373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_62452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49980.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_84467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148291.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120214.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75712.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108118.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_41311.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22010.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_167081.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158648.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142189.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74779.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_7995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16413.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91590.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187611.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199259.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74199.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_119042.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154603.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_100466.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101595.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_190231.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_40153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_185542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_169924.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_139608.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159767.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_150810.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116650.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21419.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134990.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105499.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216535.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_172563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_124605.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35549.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_113417.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116613.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_201025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129247.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11221.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27724.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_183920.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118556.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12930.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199276.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192800.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48336.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_63633.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11240.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36091.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_23752.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102262.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_28134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_37846.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207483.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162577.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_115855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_200925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_184218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178212.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158985.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_119854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21735.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_169386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29362.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_60790.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121275.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_51746.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_165646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135049.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_116418.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182590.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216289.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137595.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114277.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_37094.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146817.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58080.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102264.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_9281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57965.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_191057.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_145745.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132495.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68007.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11933.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174506.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120267.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_145870.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170435.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149699.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209471.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2471.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_128086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_167527.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2570.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12797.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207248.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157192.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_163434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_201715.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_5634.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27166.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44222.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_47196.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_86984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_14968.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_164836.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149638.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_147646.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_100900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146197.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_82624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101823.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_66412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_7975.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_84411.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_113741.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_183731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_208827.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_181351.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110354.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_113241.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175842.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_147857.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_153176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_176175.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_59850.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93120.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_83713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_56336.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159117.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_51149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158453.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213874.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30833.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216246.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_176763.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22229.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_47170.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_63458.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143451.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70787.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_28241.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_127104.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26550.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_180165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79387.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174183.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187244.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_141866.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211641.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_78373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209188.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177796.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_125626.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_156000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_151885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16139.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_164778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_167861.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_50283.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_190350.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159820.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_60933.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_153565.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_126284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_205260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_215423.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_103694.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68313.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48939.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_37187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157571.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144745.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213466.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24674.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_125016.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32097.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166598.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_56539.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95185.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_208859.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_54415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_208540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_164746.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_81224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55168.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_61542.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_65064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93371.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134242.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91454.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148253.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17344.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_188737.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_111624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177328.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_43851.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117029.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55976.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11819.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_47232.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_10618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212955.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93548.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_172612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170937.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11098.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133418.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11223.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22961.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77498.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_84130.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97050.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26081.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_128135.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179459.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_51038.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17328.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144697.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212146.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110230.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_136331.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143895.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211782.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20317.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_119026.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_100662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68175.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146957.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_85134.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_151950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22942.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105787.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_37757.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98245.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_14190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6402.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96491.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25562.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_14945.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132265.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161035.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_19652.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206393.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138331.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159355.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197135.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170945.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192627.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146036.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_115926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_183196.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91683.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_59213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_171910.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88905.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_176747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_104049.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_124099.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32687.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144996.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212986.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158627.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189137.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70345.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12462.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2266.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187500.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_216488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_4925.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_190510.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_181939.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39946.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_173052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_59243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_73148.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79562.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_60920.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_84226.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44201.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_64603.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6056.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_173734.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_10177.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_19105.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1899.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_184132.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98825.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132347.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_9004.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_113788.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95173.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_121126.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_81361.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_203102.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202414.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_181968.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49985.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177337.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29794.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20418.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174050.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134224.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211917.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195714.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45275.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16080.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_122314.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22628.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_191698.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_115553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_176412.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_78879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42128.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154366.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_52813.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_89796.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_215411.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_34218.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_5006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158644.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_131194.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36950.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_171470.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_84983.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_201995.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_11743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_164423.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98533.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_25204.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80253.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45609.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96559.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_14624.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_119798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21783.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8572.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45927.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_183922.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137594.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53046.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_63325.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_161909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55714.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_160805.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_160119.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_183751.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93135.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175579.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_131618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159299.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_126165.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_151156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_56027.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93330.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213077.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68708.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49423.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_215947.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_100681.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_112040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209100.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210626.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_147000.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_147585.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53555.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_196128.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_18221.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198274.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_51919.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_102506.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_151453.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_31864.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166626.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32259.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_90365.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114323.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35146.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_127637.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_128091.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143769.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_59434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_140930.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_51310.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135190.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75324.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_112602.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_99912.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_152928.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_78931.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_106988.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_176858.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44573.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_125711.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_60915.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_81854.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114359.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_89940.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_105290.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_166389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134568.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_90415.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_84437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_49429.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_56728.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133018.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143227.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79750.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_208516.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_54693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101885.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27434.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_4159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_213791.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_104467.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142551.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_164214.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120463.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42496.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3805.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_120005.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_191187.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_111472.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_125512.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144474.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53849.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135206.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_191572.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_206286.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_124151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_52727.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_5984.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_58352.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_5161.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_4879.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123686.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22765.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123284.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_139553.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129662.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155107.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74731.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57078.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_124756.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_72798.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_165880.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95816.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_81907.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_62052.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_17200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123351.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177971.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_10233.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95538.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_93689.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_7725.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_65448.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16745.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_19367.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_198474.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142433.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144736.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170454.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_217285.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109341.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_41895.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_33263.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107387.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_164159.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68414.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_55656.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_183987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158444.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186101.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2741.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94088.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_131309.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142222.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2215.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30158.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42153.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109006.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_15228.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53066.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186332.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_95606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13487.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79817.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_72151.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_171747.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_89440.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36469.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77389.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_167509.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158606.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187438.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_176887.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_135926.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_129867.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_162067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30200.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_23403.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157093.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_145721.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35561.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96494.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_180604.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_72732.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_119045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108108.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44417.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_170428.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_65521.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177401.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_88991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_145835.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209486.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_183444.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_34861.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_2718.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_90037.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70377.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_180480.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_39678.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_71367.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107287.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138219.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_188563.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75129.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_139613.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_62859.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178084.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138089.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_31032.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109251.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_131682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75780.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_164618.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_205373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6438.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53243.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_169862.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_154391.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_104587.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_209404.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79830.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_207119.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_173056.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38026.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_68444.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_173985.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_210695.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48898.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_13632.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48736.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_183476.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_152844.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_65996.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_165540.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_185693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38977.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_114668.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_3156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_29497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175742.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_176425.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_171814.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_69702.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_90147.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109824.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123888.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158116.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_43593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_208568.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_76049.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48890.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_46270.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_34631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_59062.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_9044.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_62883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_146176.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187042.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_122424.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_208167.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186631.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_45987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_7651.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_144619.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_199808.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_140935.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38318.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_142743.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110710.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74368.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_211193.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_34464.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_35826.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175779.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79021.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_32508.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_165644.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_139072.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_173736.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_83406.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87304.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_98908.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_76630.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155322.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77530.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109367.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108025.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_150682.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_36213.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_155473.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_182584.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179357.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179710.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187225.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_130518.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_143432.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_47693.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16008.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_148017.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_14573.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_167067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_203478.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94493.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_24544.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_157713.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_178379.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101106.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187087.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_73793.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_140981.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_15260.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_930.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_89564.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_8633.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_77478.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134042.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_167255.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_194121.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_5439.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_33514.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109323.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_48301.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91520.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_75921.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_179507.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_149204.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_38067.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_61811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_115531.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_51375.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108497.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_192536.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_30488.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_215487.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_12785.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_188481.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_76454.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_20252.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_71987.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212655.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_96593.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_22891.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_28040.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_145821.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_108321.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_27641.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123329.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74909.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_15442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_74811.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53455.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_21064.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_41386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193373.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_94452.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117612.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133003.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_188449.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_89930.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_118959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187441.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_40905.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138437.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_15652.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_189303.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_7835.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_202278.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_34214.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_195195.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_186948.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_123268.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_43616.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_153778.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_152959.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53135.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117613.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_42228.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_164675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_174557.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_101198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_134883.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_44354.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_175716.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_84198.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_46079.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_41569.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_138384.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_132085.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_6086.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_160552.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158281.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_109914.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91865.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_4855.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_64978.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_62847.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_79012.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_15138.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_164045.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159733.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_183777.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_1051.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_81484.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91196.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_167386.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_117149.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204954.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_82156.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_159033.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_107442.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197039.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57900.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_80323.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_194806.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57591.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_177180.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70182.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16252.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_70991.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_212237.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_91639.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_204868.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_33677.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_26739.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_193110.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_76944.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110122.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187732.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_10127.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_112558.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_217395.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_158837.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_133277.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_92058.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_57675.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_16698.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_141953.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_87115.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_197408.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_97923.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_110524.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_200620.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_62617.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_53724.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_137014.qa.bqv
/cvmfs/data.galaxyproject.org/byhand/felCat3/quality_scores/scaffold_187239.qa.bqv
